/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForStudents;

import DB.DBConnection;
import DB.StudentCredentials;
import DB.StudentPageLogout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page3_Interact extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date

    /**
     * Creates new form Page2_Dashboard
     */
    public Page3_Interact() {        
        initComponents();
        getCourseForQuery();
        getCourseForComment();

        // center the form
        this.setLocationRelativeTo(this);
        
        Thread t = new Thread(this);
        t.start();
        
        
        comboCourseQuery.setVisible(true);
        comboStageQuery.setVisible(true);
        comboCourseComment.setVisible(false);
        comboStageComment.setVisible(false);        
        comboSerialQuery.setVisible(false);
        comboSerialComment.setVisible(false);
        
        // displaying users info
        sideBarFname.setText(StudentCredentials.fullname);
        sideBarOperator.setText(StudentCredentials.operator_id); 
        topBarRegNo.setText(StudentCredentials.reg_no);
        queryRegNo.setText(StudentCredentials.reg_no); 
        queryFname.setText(StudentCredentials.fullname); 
        commentRegNo.setText(StudentCredentials.reg_no); 
        commentFname.setText(StudentCredentials.fullname); 
    }
    
    PreparedStatement sqlSubmitQuery;
    PreparedStatement sqlSubmitComment;
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryLogout;
    ResultSet res;
    Connection conn;
    
    private void getCourseForQuery() {
        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("SELECT course_name from tbl_students_course");
            ResultSet rs = sqlQueryCheck.executeQuery();
            
            while(rs.next()) {
                comboCourseQuery.addItem(rs.getString("course_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getCourseForComment() {
        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("SELECT course_name from tbl_students_course");
            ResultSet rs = sqlQueryCheck.executeQuery();
            
            while(rs.next()) {
                comboCourseComment.addItem(rs.getString("course_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        sideBarFname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtInteract = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        txtFeedback = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        txtSettings = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topBarRegNo = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        btnGoToQuery = new javax.swing.JButton();
        btnGoToComment = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        queryFname = new javax.swing.JLabel();
        queryRegNo = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        comboUnitQuery = new javax.swing.JComboBox<>();
        comboFnameQuery = new javax.swing.JComboBox<>();
        jPanel48 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuery = new javax.swing.JTextArea();
        comboSerialQuery = new javax.swing.JComboBox<>();
        jPanel41 = new javax.swing.JPanel();
        btnSubmitQuery = new javax.swing.JButton();
        btnClearQuery = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        commentFname = new javax.swing.JLabel();
        commentRegNo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        comboUnitComment = new javax.swing.JComboBox<>();
        comboFnameComment = new javax.swing.JComboBox<>();
        jPanel50 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        comboSerialComment = new javax.swing.JComboBox<>();
        jPanel42 = new javax.swing.JPanel();
        btnSubmitComment = new javax.swing.JButton();
        btnClearComment = new javax.swing.JButton();
        comboCourseComment = new javax.swing.JComboBox<>();
        comboStageComment = new javax.swing.JComboBox<>();
        comboCourseQuery = new javax.swing.JComboBox<>();
        comboStageQuery = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masomo");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Bora");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holder1.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 160, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });
        jPanel34.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jPanel34.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 150, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInteract.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtInteract.setForeground(new java.awt.Color(255, 255, 255));
        txtInteract.setText("Interact");
        txtInteract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInteract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInteractMouseClicked(evt);
            }
        });
        jPanel37.add(txtInteract, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/interact.png"))); // NOI18N
        jPanel37.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 150, 30));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFeedback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtFeedback.setForeground(new java.awt.Color(255, 255, 255));
        txtFeedback.setText("Feedback");
        txtFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFeedbackMouseClicked(evt);
            }
        });
        jPanel38.add(txtFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/feedback.png"))); // NOI18N
        jPanel38.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 150, 30));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings.setText("Settings");
        txtSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettingsMouseClicked(evt);
            }
        });
        jPanel39.add(txtSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel39.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 150, 30));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Logout");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        jPanel32.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setText("Interaction Page");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 200, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.windowBorder);
        jLabel8.setText("Reg No:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        topBarRegNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel5.add(topBarRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 100, 17));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel5.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 17));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 600, 90));

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoToQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToQuery.setText("Query");
        btnGoToQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToQueryActionPerformed(evt);
            }
        });
        jPanel40.add(btnGoToQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        btnGoToComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToComment.setText("Comment");
        btnGoToComment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToCommentActionPerformed(evt);
            }
        });
        jPanel40.add(btnGoToComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel1.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 32));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Query Submission Form");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 490, 40));

        jPanel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel47.setOpaque(false);
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel26.setForeground(java.awt.SystemColor.windowBorder);
        jLabel26.setText("Unit Name:");
        jPanel47.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel41.setForeground(java.awt.SystemColor.windowBorder);
        jLabel41.setText("Fullname:");
        jPanel47.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        queryFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel47.add(queryFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 20));

        queryRegNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel47.add(queryRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setForeground(java.awt.SystemColor.windowBorder);
        jLabel28.setText("Reg No:");
        jPanel47.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setForeground(java.awt.SystemColor.windowBorder);
        jLabel32.setText("Lecturer Name:");
        jPanel47.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, -1));

        comboUnitQuery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUnitQueryItemStateChanged(evt);
            }
        });
        jPanel47.add(comboUnitQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 30));

        comboFnameQuery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFnameQueryItemStateChanged(evt);
            }
        });
        jPanel47.add(comboFnameQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 220, 30));

        jPanel7.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 527, 120));

        jPanel48.setOpaque(false);
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Query Section:");
        jPanel48.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtQuery.setColumns(20);
        txtQuery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuery.setForeground(java.awt.Color.gray);
        txtQuery.setLineWrap(true);
        txtQuery.setRows(5);
        txtQuery.setText("start typing ...");
        txtQuery.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtQuery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQueryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQueryFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtQuery);

        jPanel48.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 520, 120));

        jPanel7.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 527, 150));

        jPanel7.add(comboSerialQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 350, 140, 30));

        jPanel41.setOpaque(false);
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSubmitQuery.setText("Submit");
        btnSubmitQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitQueryActionPerformed(evt);
            }
        });
        jPanel41.add(btnSubmitQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 95, 31));

        btnClearQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearQuery.setText("Clear");
        btnClearQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearQueryActionPerformed(evt);
            }
        });
        jPanel41.add(btnClearQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 95, 31));

        jPanel7.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, -1, 30));

        jTabbedPane1.addTab("tab1", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Comment Submission Form");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 490, 40));

        jPanel49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel49.setOpaque(false);
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel27.setForeground(java.awt.SystemColor.windowBorder);
        jLabel27.setText("Unit Name:");
        jPanel49.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel42.setForeground(java.awt.SystemColor.windowBorder);
        jLabel42.setText("Fullname:");
        jPanel49.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        commentFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel49.add(commentFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 20));

        commentRegNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel49.add(commentRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setForeground(java.awt.SystemColor.windowBorder);
        jLabel30.setText("Reg No:");
        jPanel49.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setForeground(java.awt.SystemColor.windowBorder);
        jLabel33.setText("Lecturer Name:");
        jPanel49.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, -1));

        comboUnitComment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUnitCommentItemStateChanged(evt);
            }
        });
        jPanel49.add(comboUnitComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 30));

        comboFnameComment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFnameCommentItemStateChanged(evt);
            }
        });
        jPanel49.add(comboFnameComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 220, 30));

        jPanel8.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 527, 120));

        jPanel50.setOpaque(false);
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Comment Section:");
        jPanel50.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtComment.setColumns(20);
        txtComment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtComment.setForeground(java.awt.Color.gray);
        txtComment.setLineWrap(true);
        txtComment.setRows(5);
        txtComment.setText("start typing ...");
        txtComment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCommentFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txtComment);

        jPanel50.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 520, 120));

        jPanel8.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 527, 150));

        jPanel8.add(comboSerialComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 350, 140, 30));

        jPanel42.setOpaque(false);
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSubmitComment.setText("Submit");
        btnSubmitComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitCommentActionPerformed(evt);
            }
        });
        jPanel42.add(btnSubmitComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 95, 31));

        btnClearComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearComment.setText("Clear");
        btnClearComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCommentActionPerformed(evt);
            }
        });
        jPanel42.add(btnClearComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 95, 31));

        jPanel8.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, -1, 30));

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 560, 430));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 560, 400));

        comboCourseComment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCourseCommentItemStateChanged(evt);
            }
        });
        jPanel1.add(comboCourseComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, 30));

        comboStageComment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboStageCommentItemStateChanged(evt);
            }
        });
        jPanel1.add(comboStageComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 190, 30));

        comboCourseQuery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCourseQueryItemStateChanged(evt);
            }
        });
        jPanel1.add(comboCourseQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, 30));

        comboStageQuery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboStageQueryItemStateChanged(evt);
            }
        });
        jPanel1.add(comboStageQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtInteractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInteractMouseClicked
        // Go to lecturer
        Page3_Interact startInt = new Page3_Interact();
        this.dispose();
        startInt.setVisible(true);
    }//GEN-LAST:event_txtInteractMouseClicked

    private void txtFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFeedbackMouseClicked
        // Go to students
        Page4_Feedback feedb = new Page4_Feedback();
        this.dispose();
        feedb.setVisible(true);
    }//GEN-LAST:event_txtFeedbackMouseClicked

    private void txtSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettingsMouseClicked
        // Go to settings
        Page5_Settings pwd = new Page5_Settings();
        this.dispose();
        pwd.setVisible(true);
    }//GEN-LAST:event_txtSettingsMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // operation for login out
        String regNo = topBarRegNo.getText();
        
        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_students SET status='Offline' WHERE reg_no=? ");
            sqlQueryLogout.setString(1, regNo);
            
            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_Login login = new Page1_Login();

                // logout function
                StudentPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel25MouseClicked

    private void btnGoToQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToQueryActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        comboCourseQuery.setVisible(true);
        comboStageQuery.setVisible(true);
        comboCourseComment.setVisible(false);
        comboStageComment.setVisible(false);
    }//GEN-LAST:event_btnGoToQueryActionPerformed

    private void btnGoToCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToCommentActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        comboCourseQuery.setVisible(false);
        comboStageQuery.setVisible(false);
        comboCourseComment.setVisible(true);
        comboStageComment.setVisible(true);
    }//GEN-LAST:event_btnGoToCommentActionPerformed

    private void comboCourseQueryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCourseQueryItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT semester_level from tbl_lecturers_course where course_name= '"+comboCourseQuery.getSelectedItem()+"' ";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboStageQuery.removeAllItems();
            
            while(rs.next()) {
                comboStageQuery.addItem(rs.getString("semester_level"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboCourseQueryItemStateChanged

    private void comboStageQueryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboStageQueryItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT unit_name from tbl_lecturers_course where course_name= '"+comboCourseQuery.getSelectedItem()+"' and semester_level= '"+comboStageQuery.getSelectedItem()+"'";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboUnitQuery.removeAllItems();
            
            while(rs.next()) {
                comboUnitQuery.addItem(rs.getString("unit_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboStageQueryItemStateChanged

    private void comboUnitQueryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUnitQueryItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT fullname from tbl_lecturers_course where course_name= '"+comboCourseQuery.getSelectedItem()+"' and semester_level= '"+comboStageQuery.getSelectedItem()+"' and unit_name= '"+comboUnitQuery.getSelectedItem()+"'";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboFnameQuery.removeAllItems();
            
            while(rs.next()) {
                comboFnameQuery.addItem(rs.getString("fullname"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboUnitQueryItemStateChanged

    private void comboFnameQueryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFnameQueryItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT serial_no from tbl_lecturers_course where course_name= '"+comboCourseQuery.getSelectedItem()+"' and semester_level= '"+comboStageQuery.getSelectedItem()+"' and unit_name= '"+comboUnitQuery.getSelectedItem()+"' and fullname= '"+comboFnameQuery.getSelectedItem()+"' ";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboSerialQuery.removeAllItems();
            
            while(rs.next()) {
                comboSerialQuery.addItem(rs.getString("serial_no"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboFnameQueryItemStateChanged

    private void txtQueryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQueryFocusGained
        // operation that occur when this field is clicked
        if(txtQuery.getText().trim().toLowerCase().equals("start typing ...")){
            txtQuery.setText("");
            txtQuery.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtQueryFocusGained

    private void txtQueryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQueryFocusLost
        // operation that occur when this field is not clicked
        if(txtQuery.getText().trim().equals("") || txtQuery.getText().trim().equals("start typing ...")){
            txtQuery.setText("start typing ...");
            txtQuery.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtQueryFocusLost

    private void btnSubmitQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitQueryActionPerformed
        // operation for sending a query
        // student variables
        String unitName   = comboUnitQuery.getSelectedItem().toString();
        String studFname  = queryFname.getText();
        String studId     = queryRegNo.getText();
        String lecFname   = comboFnameQuery.getSelectedItem().toString();
        String lecId      = comboSerialQuery.getSelectedItem().toString();
        String msgContent = txtQuery.getText();
        String msgStatus  = "Pending";
        String dateSent   = txtDate.getText();
        String senderLbl  = "Query";
        
        // auto generated variables
        String repliedMsg  = " ";
        String linkOfDoc   = " ";
        String document    = null;
        String repliedDate = " ";
        String cleared     = " ";
                
        if(msgContent.trim().equals("") || msgContent.trim().equals("start typing ...")){
            JOptionPane.showMessageDialog(null, "Cannot submit an Empty Form", "Form Submission Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                conn = DBConnection.setConnection();
                sqlSubmitQuery = conn.prepareStatement("insert into tbl_interaction (unit_name, stud_fname, stud_identifier, lec_fname, lec_identifier, msg_content, msg_status, date_sent, msg_lbl, replied_msg, link_doc, document, date_replied, doubt_cleared) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                sqlSubmitQuery.setString(1, unitName);
                sqlSubmitQuery.setString(2, studFname);
                sqlSubmitQuery.setString(3, studId);
                sqlSubmitQuery.setString(4, lecFname);
                sqlSubmitQuery.setString(5, lecId);
                sqlSubmitQuery.setString(6, msgContent);
                sqlSubmitQuery.setString(7, msgStatus);
                sqlSubmitQuery.setString(8, dateSent);
                sqlSubmitQuery.setString(9, senderLbl);
                sqlSubmitQuery.setString(10, repliedMsg);                
                sqlSubmitQuery.setString(11, linkOfDoc);
                sqlSubmitQuery.setString(12, document);
                sqlSubmitQuery.setString(13, repliedDate);
                sqlSubmitQuery.setString(14, cleared);

                //if the record is inserted successfully the state of executeUpdate() will be 1
                if (sqlSubmitQuery.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Your Query was sent successfully.");

                    // clearing the form after successfully adding the new record in the database
                    txtQuery.setText("");

                    // redirect the user to this page
                    new Page4_Feedback().setVisible(true);
                    this.dispose();

                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitQueryActionPerformed

    private void btnClearQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearQueryActionPerformed
        // clearing the form body
        txtQuery.setText("");
        if(txtQuery.getText().trim().equals("") || txtQuery.getText().trim().equals("start typing ...")){
            txtQuery.setText("start typing ...");
            txtQuery.setForeground(Color.gray);
        }
    }//GEN-LAST:event_btnClearQueryActionPerformed

    
    /**
     * form validation
     */
    private void comboCourseCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCourseCommentItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT semester_level from tbl_lecturers_course where course_name= '"+comboCourseComment.getSelectedItem()+"' ";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboStageComment.removeAllItems();
            
            while(rs.next()) {
                comboStageComment.addItem(rs.getString("semester_level"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboCourseCommentItemStateChanged

    private void comboStageCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboStageCommentItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT unit_name from tbl_lecturers_course where course_name= '"+comboCourseComment.getSelectedItem()+"' and semester_level= '"+comboStageComment.getSelectedItem()+"'";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboUnitComment.removeAllItems();
            
            while(rs.next()) {
                comboUnitComment.addItem(rs.getString("unit_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboStageCommentItemStateChanged

    private void comboUnitCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUnitCommentItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT fullname from tbl_lecturers_course where course_name= '"+comboCourseComment.getSelectedItem()+"' and semester_level= '"+comboStageComment.getSelectedItem()+"' and unit_name= '"+comboUnitComment.getSelectedItem()+"'";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboFnameComment.removeAllItems();
            
            while(rs.next()) {
                comboFnameComment.addItem(rs.getString("fullname"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboUnitCommentItemStateChanged

    private void comboFnameCommentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFnameCommentItemStateChanged
        try {
            Connection conn = DBConnection.setConnection();
            String Query = "SELECT serial_no from tbl_lecturers_course where course_name= '"+comboCourseComment.getSelectedItem()+"' and semester_level= '"+comboStageComment.getSelectedItem()+"' and unit_name= '"+comboUnitComment.getSelectedItem()+"' and fullname= '"+comboFnameComment.getSelectedItem()+"' ";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();
            
            comboSerialComment.removeAllItems();
            
            while(rs.next()) {
                comboSerialComment.addItem(rs.getString("serial_no"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboFnameCommentItemStateChanged

    private void txtCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCommentFocusGained
        // operation that occur when this field is clicked
        if(txtComment.getText().trim().toLowerCase().equals("start typing ...")) {
            txtComment.setText("");
            txtComment.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCommentFocusGained

    private void txtCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCommentFocusLost
        // operation that occur when this field is not clicked
        if(txtComment.getText().trim().equals("") || txtComment.getText().trim().equals("start typing ...")){
            txtComment.setText("start typing ...");
            txtComment.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCommentFocusLost

    private void btnSubmitCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCommentActionPerformed
        // operation for sending a comment
        // student variables
        String unitName   = comboUnitComment.getSelectedItem().toString();
        String studFname  = commentFname.getText();
        String studId     = commentRegNo.getText();
        String lecFname   = comboFnameComment.getSelectedItem().toString();
        String lecId      = comboSerialComment.getSelectedItem().toString();
        String msgContent = txtComment.getText();
        String msgStatus  = "Pending";
        String dateSent   = txtDate.getText();
        String senderLbl  = "Comment";
        
        // auto generated variables
        String repliedMsg  = " ";
        String linkOfDoc   = " ";
        String document    = null;
        String repliedDate = " ";
        String cleared     = " ";

        // checking if any field is empty before submitting the form
        if(msgContent.trim().equals("") || msgContent.trim().equals("start typing ...")){
            JOptionPane.showMessageDialog(null, "Cannot submit an Empty Form", "Form Submission Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                conn = DBConnection.setConnection();
                sqlSubmitComment = conn.prepareStatement("insert into tbl_interaction (unit_name, stud_fname, stud_identifier, lec_fname, lec_identifier, msg_content, msg_status, date_sent, msg_lbl, replied_msg, link_doc, document, date_replied, doubt_cleared) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                sqlSubmitComment.setString(1, unitName);
                sqlSubmitComment.setString(2, studFname);
                sqlSubmitComment.setString(3, studId);
                sqlSubmitComment.setString(4, lecFname);
                sqlSubmitComment.setString(5, lecId);
                sqlSubmitComment.setString(6, msgContent);
                sqlSubmitComment.setString(7, msgStatus);
                sqlSubmitComment.setString(8, dateSent);
                sqlSubmitComment.setString(9, senderLbl);
                sqlSubmitComment.setString(10, repliedMsg);                
                sqlSubmitComment.setString(11, linkOfDoc);
                sqlSubmitComment.setString(12, document);
                sqlSubmitComment.setString(13, repliedDate);
                sqlSubmitComment.setString(14, cleared);

                //if the record is inserted successfully the state of executeUpdate() will be 1
                if (sqlSubmitComment.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Your Comment was sent successfully.");

                    // clearing the form after successfully adding the new record in the database
                    txtComment.setText("");

                    // redirect the user to this page
                    new Page4_Feedback().setVisible(true);
                    this.dispose();

                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Interact.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitCommentActionPerformed

    private void btnClearCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCommentActionPerformed
        // clearing the form body
        txtComment.setText("");
        if(txtComment.getText().trim().equals("") || txtComment.getText().trim().equals("start typing ...")){
            txtComment.setText("start typing ...");
            txtComment.setForeground(Color.gray);
        }
    }//GEN-LAST:event_btnClearCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3_Interact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3_Interact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3_Interact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3_Interact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3_Interact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearComment;
    private javax.swing.JButton btnClearQuery;
    private javax.swing.JButton btnGoToComment;
    private javax.swing.JButton btnGoToQuery;
    private javax.swing.JButton btnSubmitComment;
    private javax.swing.JButton btnSubmitQuery;
    private javax.swing.JComboBox<String> comboCourseComment;
    private javax.swing.JComboBox<String> comboCourseQuery;
    private javax.swing.JComboBox<String> comboFnameComment;
    private javax.swing.JComboBox<String> comboFnameQuery;
    private javax.swing.JComboBox<String> comboSerialComment;
    private javax.swing.JComboBox<String> comboSerialQuery;
    private javax.swing.JComboBox<String> comboStageComment;
    private javax.swing.JComboBox<String> comboStageQuery;
    private javax.swing.JComboBox<String> comboUnitComment;
    private javax.swing.JComboBox<String> comboUnitQuery;
    private javax.swing.JLabel commentFname;
    private javax.swing.JLabel commentRegNo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel queryFname;
    private javax.swing.JLabel queryRegNo;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private javax.swing.JLabel topBarRegNo;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private javax.swing.JLabel txtFeedback;
    private javax.swing.JLabel txtInteract;
    private javax.swing.JTextArea txtQuery;
    private javax.swing.JLabel txtSettings;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
