/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForStudents;

import DB.DBConnection;
import DB.StudentCredentials;
import DB.StudentPageLogout;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoeAlpha
 */
public class Page4_Feedback extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date

    /**
     * Creates new form Page2_Dashboard
     */
    public Page4_Feedback() {        
        initComponents();
        feedback_table();

        // center the form
        this.setLocationRelativeTo(this);
        
        Thread t = new Thread(this);
        t.start();
        
        btnViewComment.setVisible(false);
        btnGoBack.setVisible(false);
//        btnViewSolution.setVisible(false);
        
        // displaying users info
        sideBarFname.setText(StudentCredentials.fullname);
        sideBarOperator.setText(StudentCredentials.operator_id); 
        topBarRegNo.setText(StudentCredentials.reg_no);
    }
    
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryLogout;
    ResultSet res;
    Connection conn;
    
    DefaultTableModel defaulttbl_1_feedback;
    DefaultTableModel defaulttbl_2_view;
    DefaultTableModel defaulttbl_3_viewSln;
    DefaultTableModel defaulttbl_4_viewReply;
    DefaultTableModel defaulttbl_5_download;
    
    private void feedback_table() {
        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction");
            res = sqlQueryCheck.executeQuery();
            
            while(res.next()) {
                String feedbId     = res.getString("msg_id");
                String feedbUnit   = res.getString("unit_name");
                String feedbFname  = res.getString("lec_fname");
                String feedbLbl    = res.getString("msg_lbl");
                String feedbDate   = res.getString("date_sent");
                String feedbStatus = res.getString("msg_status");
                
                Object[] obj = {feedbId, feedbUnit, feedbFname, feedbLbl, feedbDate, feedbStatus};
                
                defaulttbl_1_feedback = (DefaultTableModel)tbl_feedback.getModel();
                defaulttbl_1_feedback.addRow(obj);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        sideBarFname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtInteract = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        txtFeedback = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        txtSettings = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topBarRegNo = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        btnShowAll = new javax.swing.JButton();
        btnViewQuery = new javax.swing.JButton();
        btnViewComment = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_feedback = new rojeru_san.complementos.RSTableMetro();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        queryRetrieveLecName = new javax.swing.JLabel();
        queryRetrieveUnit = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        queryRetrieveDateSent = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryRetrieveMsg = new javax.swing.JTextArea();
        jPanel41 = new javax.swing.JPanel();
        btnViewSolution = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        replyToQueryMsg = new javax.swing.JTextArea();
        replyToRegQuery = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        replyToFnameQuery = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        queryDateSent = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        queryRetrieveMsg2 = new javax.swing.JTextArea();
        jLabel84 = new javax.swing.JLabel();
        queryDateSent2 = new javax.swing.JLabel();
        queryRetrieveLink = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        commentRetrieveLecName = new javax.swing.JLabel();
        commentRetrieveUnit = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        commentRetrieveDateSent = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        commentRetrieveMsg = new javax.swing.JTextArea();
        jPanel42 = new javax.swing.JPanel();
        btnViewReply = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        replyToCommentMsg = new javax.swing.JTextArea();
        replyToRegComment = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        replyToFnameComment = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        commentDateSent = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        commentRetrieveMsg1 = new javax.swing.JTextArea();
        jLabel82 = new javax.swing.JLabel();
        commentRepliedOn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masomo");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Bora");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holder1.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 160, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });
        jPanel34.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jPanel34.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 150, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInteract.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtInteract.setForeground(new java.awt.Color(255, 255, 255));
        txtInteract.setText("Interact");
        txtInteract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInteract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInteractMouseClicked(evt);
            }
        });
        jPanel37.add(txtInteract, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/interact.png"))); // NOI18N
        jPanel37.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 150, 30));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFeedback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtFeedback.setForeground(new java.awt.Color(255, 255, 255));
        txtFeedback.setText("Feedback");
        txtFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFeedbackMouseClicked(evt);
            }
        });
        jPanel38.add(txtFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/feedback.png"))); // NOI18N
        jPanel38.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 150, 30));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings.setText("Settings");
        txtSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettingsMouseClicked(evt);
            }
        });
        jPanel39.add(txtSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel39.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 150, 30));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Logout");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        jPanel32.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setText("My Feedback");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.windowBorder);
        jLabel8.setText("Reg No:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        topBarRegNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel5.add(topBarRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 100, 17));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel5.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 17));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 600, 90));

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel40.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        btnViewQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewQuery.setText("View");
        btnViewQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQueryActionPerformed(evt);
            }
        });
        jPanel40.add(btnViewQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 30));

        btnViewComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewComment.setText("View");
        btnViewComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommentActionPerformed(evt);
            }
        });
        jPanel40.add(btnViewComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 30));

        btnGoBack.setText("Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        jPanel40.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 100, 30));

        jPanel1.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 560, 32));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tbl_feedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# ", "Unit", "Lecturer", "Label", "Date Sent", "Status"
            }
        ));
        tbl_feedback.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbl_feedback.setColorBordeHead(new java.awt.Color(0, 112, 192));
        tbl_feedback.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_feedback.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_feedback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_feedback.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_feedback.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_feedback.setFuenteHead(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_feedback.setGrosorBordeFilas(0);
        tbl_feedback.setGrosorBordeHead(0);
        tbl_feedback.setMultipleSeleccion(false);
        tbl_feedback.setRowHeight(25);
        tbl_feedback.setShowHorizontalLines(false);
        tbl_feedback.setShowVerticalLines(false);
        tbl_feedback.getTableHeader().setReorderingAllowed(false);
        tbl_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_feedbackMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_feedback);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Content of this Query");

        jPanel52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel52.setOpaque(false);
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Unit Information");
        jPanel52.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel67.setForeground(java.awt.SystemColor.windowBorder);
        jLabel67.setText("Unit:");
        jPanel52.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel68.setForeground(java.awt.SystemColor.windowBorder);
        jLabel68.setText("Lecturer Name:");
        jPanel52.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        queryRetrieveLecName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel52.add(queryRetrieveLecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 210, 20));

        queryRetrieveUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel52.add(queryRetrieveUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 20));

        jPanel55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel55.setOpaque(false);
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setText("Query Information");
        jPanel55.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel72.setForeground(java.awt.SystemColor.windowBorder);
        jLabel72.setText("Date Sent:");
        jPanel55.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel73.setForeground(java.awt.SystemColor.windowBorder);
        jLabel73.setText("Body:");
        jPanel55.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        queryRetrieveDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel55.add(queryRetrieveDateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, 16));

        queryRetrieveMsg.setEditable(false);
        queryRetrieveMsg.setColumns(20);
        queryRetrieveMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        queryRetrieveMsg.setRows(5);
        queryRetrieveMsg.setBorder(null);
        jScrollPane4.setViewportView(queryRetrieveMsg);

        jPanel55.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 450, 90));

        jPanel41.setOpaque(false);
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewSolution.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewSolution.setText("View Solution");
        btnViewSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSolutionActionPerformed(evt);
            }
        });
        jPanel41.add(btnViewSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Replied Query");

        jPanel64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel64.setOpaque(false);
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setText("Query Information");
        jPanel64.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel81.setForeground(java.awt.SystemColor.windowBorder);
        jLabel81.setText("Reg No: ");
        jPanel64.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        replyToQueryMsg.setEditable(false);
        replyToQueryMsg.setColumns(20);
        replyToQueryMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        replyToQueryMsg.setLineWrap(true);
        replyToQueryMsg.setRows(5);
        replyToQueryMsg.setBorder(null);
        jScrollPane5.setViewportView(replyToQueryMsg);

        jPanel64.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 70));
        jPanel64.add(replyToRegQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 16));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel77.setForeground(java.awt.SystemColor.windowBorder);
        jLabel77.setText("Student Name:");
        jPanel64.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        jPanel64.add(replyToFnameQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 16));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel83.setForeground(java.awt.SystemColor.windowBorder);
        jLabel83.setText("Was sent on:");
        jPanel64.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 30));

        queryDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel64.add(queryDateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 6, 150, 20));

        jPanel65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel65.setOpaque(false);

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel85.setText("Reply Section");

        queryRetrieveMsg2.setEditable(false);
        queryRetrieveMsg2.setColumns(20);
        queryRetrieveMsg2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        queryRetrieveMsg2.setLineWrap(true);
        queryRetrieveMsg2.setRows(5);
        queryRetrieveMsg2.setBorder(null);
        jScrollPane17.setViewportView(queryRetrieveMsg2);

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel84.setForeground(java.awt.SystemColor.windowBorder);
        jLabel84.setText("Replied on:");

        queryDateSent2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        queryRetrieveLink.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        queryRetrieveLink.setForeground(new java.awt.Color(0, 112, 192));
        queryRetrieveLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        queryRetrieveLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryRetrieveLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel65Layout = new javax.swing.GroupLayout(jPanel65);
        jPanel65.setLayout(jPanel65Layout);
        jPanel65Layout.setHorizontalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel84)
                .addGap(13, 13, 13)
                .addComponent(queryDateSent2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(queryRetrieveLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel65Layout.setVerticalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel65Layout.createSequentialGroup()
                .addGroup(jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel65Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(queryDateSent2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(queryRetrieveLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel64, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(jPanel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel64, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Content of this Comment");

        jPanel54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel54.setOpaque(false);
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setText("Unit Information");
        jPanel54.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel70.setForeground(java.awt.SystemColor.windowBorder);
        jLabel70.setText("Unit:");
        jPanel54.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel75.setForeground(java.awt.SystemColor.windowBorder);
        jLabel75.setText("Lecturer Name:");
        jPanel54.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        commentRetrieveLecName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel54.add(commentRetrieveLecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 210, 20));

        commentRetrieveUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel54.add(commentRetrieveUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 20));

        jPanel57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel57.setOpaque(false);
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel78.setText("Comment Information");
        jPanel57.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel79.setForeground(java.awt.SystemColor.windowBorder);
        jLabel79.setText("Date Sent:");
        jPanel57.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel80.setForeground(java.awt.SystemColor.windowBorder);
        jLabel80.setText("Body:");
        jPanel57.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        commentRetrieveDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel57.add(commentRetrieveDateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, 16));

        commentRetrieveMsg.setEditable(false);
        commentRetrieveMsg.setColumns(20);
        commentRetrieveMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        commentRetrieveMsg.setRows(5);
        commentRetrieveMsg.setBorder(null);
        jScrollPane6.setViewportView(commentRetrieveMsg);

        jPanel57.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 450, 90));

        jPanel42.setOpaque(false);
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewReply.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewReply.setText("View Reply");
        btnViewReply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReplyActionPerformed(evt);
            }
        });
        jPanel42.add(btnViewReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab4", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Reply to this Comment");

        jPanel72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel72.setOpaque(false);

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel95.setText("Comment Information");

        jLabel96.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel96.setForeground(java.awt.SystemColor.windowBorder);
        jLabel96.setText("Reg No: ");

        replyToCommentMsg.setEditable(false);
        replyToCommentMsg.setColumns(20);
        replyToCommentMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        replyToCommentMsg.setLineWrap(true);
        replyToCommentMsg.setRows(5);
        replyToCommentMsg.setBorder(null);
        jScrollPane13.setViewportView(replyToCommentMsg);

        jLabel97.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel97.setForeground(java.awt.SystemColor.windowBorder);
        jLabel97.setText("Student Name:");

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel76.setForeground(java.awt.SystemColor.windowBorder);
        jLabel76.setText("Was sent on:");

        commentDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel72Layout.createSequentialGroup()
                        .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel72Layout.createSequentialGroup()
                                .addComponent(jLabel96)
                                .addGap(5, 5, 5)
                                .addComponent(replyToRegComment, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel95))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel72Layout.createSequentialGroup()
                                .addComponent(jLabel76)
                                .addGap(13, 13, 13)
                                .addComponent(commentDateSent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel72Layout.createSequentialGroup()
                                .addComponent(jLabel97)
                                .addGap(11, 11, 11)
                                .addComponent(replyToFnameComment, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel72Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel95)
                    .addComponent(jLabel76)
                    .addComponent(commentDateSent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel96)
                    .addComponent(replyToRegComment, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel97)
                    .addComponent(replyToFnameComment, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel73.setOpaque(false);
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel99.setText("Reply Section");
        jPanel73.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        commentRetrieveMsg1.setEditable(false);
        commentRetrieveMsg1.setColumns(20);
        commentRetrieveMsg1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        commentRetrieveMsg1.setLineWrap(true);
        commentRetrieveMsg1.setRows(5);
        commentRetrieveMsg1.setBorder(null);
        jScrollPane16.setViewportView(commentRetrieveMsg1);

        jPanel73.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 100));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel82.setForeground(java.awt.SystemColor.windowBorder);
        jLabel82.setText("Replied on:");
        jPanel73.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        commentRepliedOn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel73.add(commentRepliedOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 150, 16));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab5", jPanel11);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 560, 430));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 560, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtInteractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInteractMouseClicked
        // Go to lecturer
        Page3_Interact startInt = new Page3_Interact();
        this.dispose();
        startInt.setVisible(true);
    }//GEN-LAST:event_txtInteractMouseClicked

    private void txtFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFeedbackMouseClicked
        // Go to students
        Page4_Feedback feedb = new Page4_Feedback();
        this.dispose();
        feedb.setVisible(true);
    }//GEN-LAST:event_txtFeedbackMouseClicked

    private void txtSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettingsMouseClicked
        // Go to settings
        Page5_Settings pwd = new Page5_Settings();
        this.dispose();
        pwd.setVisible(true);
    }//GEN-LAST:event_txtSettingsMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // operation for login out
        String regNo = topBarRegNo.getText();
        
        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_students SET status='Offline' WHERE reg_no=? ");
            sqlQueryLogout.setString(1, regNo);
            
            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_Login login = new Page1_Login();

                // logout function
                StudentPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel25MouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        btnGoBack.setVisible(false);
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnViewQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQueryActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        btnGoBack.setVisible(true);
    }//GEN-LAST:event_btnViewQueryActionPerformed

    private void btnViewCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommentActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        btnGoBack.setVisible(true);
    }//GEN-LAST:event_btnViewCommentActionPerformed

    private void tbl_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_feedbackMouseClicked
        String lblQuery = "Query";
        String lblComment = "Comment";

        defaulttbl_2_view = (DefaultTableModel)tbl_feedback.getModel();
        int selectIndex = tbl_feedback.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_2_view.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String fetchUnit = res.getString("unit_name");
                String fetchLec  = res.getString("lec_fname");
                String fetchDate = res.getString("date_sent");
                String fetchMsg  = res.getString("msg_content");
                String fetchlbl  = res.getString("msg_lbl");
                
                if (fetchlbl.equals(lblQuery)){
                    btnViewQuery.setVisible(true);
                    btnViewComment.setVisible(false);
                    
                    queryRetrieveUnit.setText(fetchUnit);
                    queryRetrieveLecName.setText(fetchLec);
                    queryRetrieveDateSent.setText(fetchDate);
                    queryRetrieveMsg.setText(fetchMsg);
                }  
                else if (fetchlbl.equals(lblComment)){
                    btnViewQuery.setVisible(false);
                    btnViewComment.setVisible(true);
                    
                    commentRetrieveUnit.setText(fetchUnit);
                    commentRetrieveLecName.setText(fetchLec);
                    commentRetrieveDateSent.setText(fetchDate);
                    commentRetrieveMsg.setText(fetchMsg);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_feedbackMouseClicked

    private void btnViewSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSolutionActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        btnGoBack.setVisible(true);
        
        String cleared = "Yes";
        String cleared2 = "No";

        defaulttbl_3_viewSln = (DefaultTableModel)tbl_feedback.getModel();
        int selectIndex = tbl_feedback.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_3_viewSln.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispSentOn    = res.getString("date_sent");
                String dispStudID    = res.getString("stud_identifier");
                String dispStudFname = res.getString("stud_fname");
                String dispQuery     = res.getString("msg_content");
                String repliedOn     = res.getString("date_replied");
                String resolvedMsg   = res.getString("replied_msg");
                String docLink       = res.getString("link_doc");
                String dispClear     = res.getString("doubt_cleared");
                
                if (dispClear.equals(cleared)){
                    queryDateSent.setText(dispSentOn);
                    replyToRegQuery.setText(dispStudID);
                    replyToFnameQuery.setText(dispStudFname);
                    replyToQueryMsg.setText(dispQuery);  
                    queryDateSent2.setText(repliedOn);
                    queryRetrieveMsg2.setText(resolvedMsg);   
                    queryRetrieveLink.setText(docLink);     
                }
                else if (dispClear.equals(cleared2)){
                    queryDateSent.setText(dispSentOn);
                    replyToRegQuery.setText(dispStudID);
                    replyToFnameQuery.setText(dispStudFname);
                    replyToQueryMsg.setText(dispQuery);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewSolutionActionPerformed

    private void btnViewReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReplyActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        btnGoBack.setVisible(true);
        
        String cleared = "Yes";
        String cleared2 = "No";
                
        defaulttbl_4_viewReply = (DefaultTableModel)tbl_feedback.getModel();
        int selectIndex = tbl_feedback.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_4_viewReply.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispSentOn    = res.getString("date_sent");
                String dispStudID    = res.getString("stud_identifier");
                String dispStudFname = res.getString("stud_fname");
                String dispComment   = res.getString("msg_content");
                String repliedOn     = res.getString("date_replied");
                String resolvedMsg   = res.getString("replied_msg");
                String dispClear     = res.getString("doubt_cleared");

                if (dispClear.equals(cleared)){
                    commentDateSent.setText(dispSentOn);
                    replyToRegComment.setText(dispStudID);
                    replyToFnameComment.setText(dispStudFname);
                    replyToCommentMsg.setText(dispComment);   
                    commentRepliedOn.setText(repliedOn);
                    commentRetrieveMsg1.setText(resolvedMsg);        
                }
                else if (dispClear.equals(cleared2)){
                    commentDateSent.setText(dispSentOn);
                    replyToRegComment.setText(dispStudID);
                    replyToFnameComment.setText(dispStudFname);
                    replyToCommentMsg.setText(dispComment); 
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewReplyActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        btnGoBack.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void queryRetrieveLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryRetrieveLinkMouseClicked
        // downloading the document
        defaulttbl_5_download = (DefaultTableModel)tbl_feedback.getModel();
        int selectIndex = tbl_feedback.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_5_download.getValueAt(selectIndex, 0).toString());
        String fileSaveAs = queryRetrieveLink.getText();
        
        try {
            Connection conn = DBConnection.setConnection();
            PreparedStatement sqlDownload = conn.prepareStatement("select * from tbl_interaction where msg_id=? ");
            sqlDownload.setInt(1, id);            
            ResultSet res = sqlDownload.executeQuery();
            
            if(res.next()) {
                Blob b = res.getBlob("document");
                
                byte[] byte_array = b.getBytes(1, (int)b.length());
                FileOutputStream fos = new FileOutputStream(fileSaveAs);
                fos.write(byte_array);
                fos.close();
                
                JOptionPane.showMessageDialog(null, "Your document will be downloaded to " + " " + fileSaveAs);
                JOptionPane.showMessageDialog(null, "File has been Downloaded successfully");
            }

            // closing the DB connection
            conn.close();
        } catch (Exception ex) {
            Logger.getLogger(Page4_Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_queryRetrieveLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page4_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page4_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page4_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page4_Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page4_Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnViewComment;
    private javax.swing.JButton btnViewQuery;
    private javax.swing.JButton btnViewReply;
    private javax.swing.JButton btnViewSolution;
    private javax.swing.JLabel commentDateSent;
    private javax.swing.JLabel commentRepliedOn;
    private javax.swing.JLabel commentRetrieveDateSent;
    private javax.swing.JLabel commentRetrieveLecName;
    private javax.swing.JTextArea commentRetrieveMsg;
    private javax.swing.JTextArea commentRetrieveMsg1;
    private javax.swing.JLabel commentRetrieveUnit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel queryDateSent;
    private javax.swing.JLabel queryDateSent2;
    private javax.swing.JLabel queryRetrieveDateSent;
    private javax.swing.JLabel queryRetrieveLecName;
    private javax.swing.JLabel queryRetrieveLink;
    private javax.swing.JTextArea queryRetrieveMsg;
    private javax.swing.JTextArea queryRetrieveMsg2;
    private javax.swing.JLabel queryRetrieveUnit;
    private javax.swing.JTextArea replyToCommentMsg;
    private javax.swing.JLabel replyToFnameComment;
    private javax.swing.JLabel replyToFnameQuery;
    private javax.swing.JTextArea replyToQueryMsg;
    private javax.swing.JLabel replyToRegComment;
    private javax.swing.JLabel replyToRegQuery;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private rojeru_san.complementos.RSTableMetro tbl_feedback;
    private javax.swing.JLabel topBarRegNo;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private javax.swing.JLabel txtFeedback;
    private javax.swing.JLabel txtInteract;
    private javax.swing.JLabel txtSettings;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
