/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForLecturer;

import DB.DBConnection;
import DB.LecturerCredentials;
import DB.LecturerPageLogout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page5_Settings extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date

    /**
     * Creates new form Page2_Dashboard
     */
    public Page5_Settings() {        
        initComponents();

        // center the form
        this.setLocationRelativeTo(this);
        
        Thread t = new Thread(this);
        t.start();
        
        // displaying users info
        sideBarFname.setText(LecturerCredentials.fullname);
        sideBarOperator.setText(LecturerCredentials.operator_id);   
        topBarSerialNo.setText(LecturerCredentials.serial_no);
        lblGreet.setText(LecturerCredentials.fullname);
    }
    
    
    PreparedStatement sqlQueryUpdate;
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryLogout;
    ResultSet res;
    Connection conn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        sideBarFname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtQueries = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        txtOverview = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        txtSettings = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topBarSerialNo = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        btnUpdtPwd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        passwordBar1 = new javax.swing.JTextField();
        txtCurrentPwd = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        pwdError1 = new javax.swing.JLabel();
        passwordBar2 = new javax.swing.JTextField();
        pwdError2 = new javax.swing.JLabel();
        txtNewPwd = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        passwordBar3 = new javax.swing.JTextField();
        txtConfirmPwd = new javax.swing.JPasswordField();
        jLabel33 = new javax.swing.JLabel();
        pwdError3 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblGreet = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masomo");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Bora");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holder1.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 160, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });
        jPanel34.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jPanel34.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 150, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQueries.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtQueries.setForeground(new java.awt.Color(255, 255, 255));
        txtQueries.setText("Queries");
        txtQueries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtQueries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQueriesMouseClicked(evt);
            }
        });
        jPanel37.add(txtQueries, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/interact.png"))); // NOI18N
        jPanel37.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 150, 30));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOverview.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtOverview.setForeground(new java.awt.Color(255, 255, 255));
        txtOverview.setText("Overview");
        txtOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOverviewMouseClicked(evt);
            }
        });
        jPanel38.add(txtOverview, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/feedback.png"))); // NOI18N
        jPanel38.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 150, 30));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings.setText("Settings");
        txtSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettingsMouseClicked(evt);
            }
        });
        jPanel39.add(txtSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel39.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 150, 30));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Logout");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        jPanel32.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setText("Settings");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.windowBorder);
        jLabel8.setText("Serial No:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        topBarSerialNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel5.add(topBarSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 60, 100, 17));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel5.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 17));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 600, 90));

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel41.setOpaque(false);
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdtPwd.setBackground(java.awt.SystemColor.textHighlight);
        btnUpdtPwd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdtPwd.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdtPwd.setText("Update");
        btnUpdtPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdtPwdActionPerformed(evt);
            }
        });
        jPanel41.add(btnUpdtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Current :");
        jPanel41.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Confirm :");
        jPanel41.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("New :");
        jPanel41.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 30));

        passwordBar1.setBackground(java.awt.Color.darkGray);
        passwordBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel41.add(passwordBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 1));

        txtCurrentPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCurrentPwd.setForeground(java.awt.Color.gray);
        txtCurrentPwd.setText("yourpassword");
        txtCurrentPwd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCurrentPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCurrentPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCurrentPwdFocusLost(evt);
            }
        });
        jPanel41.add(txtCurrentPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 160, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel41.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 30, 30));

        pwdError1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pwdError1.setForeground(java.awt.Color.red);
        jPanel41.add(pwdError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 210, 20));

        passwordBar2.setBackground(java.awt.Color.darkGray);
        passwordBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel41.add(passwordBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, 1));

        pwdError2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pwdError2.setForeground(java.awt.Color.red);
        jPanel41.add(pwdError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 300, 20));

        txtNewPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNewPwd.setForeground(java.awt.Color.gray);
        txtNewPwd.setText("yourpassword");
        txtNewPwd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNewPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusLost(evt);
            }
        });
        txtNewPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPwdKeyReleased(evt);
            }
        });
        jPanel41.add(txtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel41.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 30, 30));

        passwordBar3.setBackground(java.awt.Color.darkGray);
        passwordBar3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel41.add(passwordBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 1));

        txtConfirmPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtConfirmPwd.setForeground(java.awt.Color.gray);
        txtConfirmPwd.setText("yourpassword");
        txtConfirmPwd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConfirmPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusLost(evt);
            }
        });
        jPanel41.add(txtConfirmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel41.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, 30));

        pwdError3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pwdError3.setForeground(java.awt.Color.red);
        jPanel41.add(pwdError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 300, 20));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel82.setText("Change Password:");
        jPanel41.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jPanel40.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 480, 310));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("If your current password isn't secure anymore, feel free to change it");
        jPanel40.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 430, 30));

        lblGreet.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGreet.setForeground(java.awt.SystemColor.textHighlight);
        jPanel40.add(lblGreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 360, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setText("Hello");
        jPanel40.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 40));

        jPanel1.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 550, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtQueriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQueriesMouseClicked
        // Go to Queries
        Page3_Queries startInt = new Page3_Queries();
        this.dispose();
        startInt.setVisible(true);
    }//GEN-LAST:event_txtQueriesMouseClicked

    private void txtOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOverviewMouseClicked
        // Go to overview
        Page4_Overview overVW = new Page4_Overview();
        this.dispose();
        overVW.setVisible(true);
    }//GEN-LAST:event_txtOverviewMouseClicked

    private void txtSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettingsMouseClicked
        // Go to settings
        Page5_Settings pwd = new Page5_Settings();
        this.dispose();
        pwd.setVisible(true);
    }//GEN-LAST:event_txtSettingsMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // operation for login out
        String serialNo = topBarSerialNo.getText();
        
        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_lecturers SET status='Offline' WHERE serial_no=? ");
            sqlQueryLogout.setString(1, serialNo);
            
            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_Login login = new Page1_Login();

                // include logout function
                LecturerPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page5_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void btnUpdtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdtPwdActionPerformed
        // operation for changing the password
        String serialNo = topBarSerialNo.getText();
        String current  = String.valueOf(txtCurrentPwd.getPassword());
        String newpwd   = String.valueOf(txtNewPwd.getPassword());
        String confpwd  = String.valueOf(txtConfirmPwd.getPassword());

        // checking if any field is empty before submitting the form
        if(current.trim().equals("") || current.trim().equals("yourpassword")){
            pwdError1.setText("Password is missing!");
        }
        else if(newpwd.trim().equals("") || newpwd.trim().equals("yourpassword")){
            pwdError2.setText("Password is missing!");
        }
        else if(confpwd.trim().equals("") || confpwd.trim().equals("yourpassword")){
            pwdError3.setText("Password is missing!");
        }
        else {  
            try {
                // checking if user credential already exist
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_lecturers where serial_no=?");
                sqlQueryCheck.setString(1, serialNo);
                res = sqlQueryCheck.executeQuery();
            
                // if the username match with the one in the database then Proceed
                if(res.next()){
                    // retrieve the password in the db
                    String retrievePass = res.getString("password");
                
                    // checking if password provided matches with the one in the database
                    if (retrievePass.equals(current)) {
                        // checking if new password is the same as confirm password
                        if (newpwd.equals(confpwd)) {
                            // update the password which is in the database
                            sqlQueryUpdate = conn.prepareStatement("update tbl_lecturers SET password=? WHERE serial_no=? ");
                            sqlQueryUpdate.setString(1, newpwd);
                            sqlQueryUpdate.setString(2, serialNo);
                        
                            if (sqlQueryUpdate.executeUpdate() != 0) {
                                // Show success mesage
                                JOptionPane.showMessageDialog(this, "Password changed successfully.");
                                JOptionPane.showMessageDialog(this, "Next time use your new password to login");

                                txtCurrentPwd.setText("yourpassword");
                                txtNewPwd.setText("yourpassword");
                                txtConfirmPwd.setText("yourpassword");

                                // redirect the user to profile page
                                new Page2_Dashboard().setVisible(true);
                                this.dispose();

                                return;
                            }
                        }
                        else {
                            pwdError3.setText("Confirm Password doesn't match with new Password!");
                            txtConfirmPwd.setText("");

                            txtConfirmPwd.requestFocus();
                        }
                    }
                    else {
                        pwdError1.setText("Invalid Password!");
                        txtCurrentPwd.setText("");

                        txtCurrentPwd.requestFocus();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page5_Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdtPwdActionPerformed

    private void txtCurrentPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPwdFocusGained
        String pwd = String.valueOf(txtCurrentPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtCurrentPwd.setText("");
            txtCurrentPwd.setForeground(Color.black);
            passwordBar1.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtCurrentPwdFocusGained

    private void txtCurrentPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrentPwdFocusLost
        String pwd = String.valueOf(txtCurrentPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtCurrentPwd.setText("yourpassword");
            txtCurrentPwd.setForeground(Color.gray);
            passwordBar1.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtCurrentPwdFocusLost

    private void txtNewPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusGained
        String pwd = String.valueOf(txtNewPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtNewPwd.setText("");
            txtNewPwd.setForeground(Color.black);
            passwordBar2.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtNewPwdFocusGained

    private void txtNewPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusLost
        String pwd = String.valueOf(txtNewPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtNewPwd.setText("yourpassword");
            txtNewPwd.setForeground(Color.gray);
            passwordBar2.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtNewPwdFocusLost

    private void txtNewPwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPwdKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtNewPwd.getText());

        if(!match.matches()) {
            pwdError2.setText("Invalid Password/use atleast 10 characters or more!");
        } else {
            pwdError2.setText(null);
        }
    }//GEN-LAST:event_txtNewPwdKeyReleased

    private void txtConfirmPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusGained
        String pwd = String.valueOf(txtConfirmPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtConfirmPwd.setText("");
            txtConfirmPwd.setForeground(Color.black);
            passwordBar3.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtConfirmPwdFocusGained

    private void txtConfirmPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusLost
        String pwd = String.valueOf(txtConfirmPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtConfirmPwd.setText("yourpassword");
            txtConfirmPwd.setForeground(Color.gray);
            passwordBar3.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtConfirmPwdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page5_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page5_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page5_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page5_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page5_Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdtPwd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JTextField passwordBar1;
    private javax.swing.JTextField passwordBar2;
    private javax.swing.JTextField passwordBar3;
    private javax.swing.JLabel pwdError1;
    private javax.swing.JLabel pwdError2;
    private javax.swing.JLabel pwdError3;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private javax.swing.JLabel topBarSerialNo;
    private javax.swing.JPasswordField txtConfirmPwd;
    private javax.swing.JPasswordField txtCurrentPwd;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private javax.swing.JPasswordField txtNewPwd;
    private javax.swing.JLabel txtOverview;
    private javax.swing.JLabel txtQueries;
    private javax.swing.JLabel txtSettings;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
