/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForLecturer;

import DB.DBConnection;
import DB.LecturerCredentials;
import DB.LecturerPageLogout;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoeAlpha
 */
public class Page3_Queries extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date

    /**
     * Creates new form Page2_Dashboard
     */
    public Page3_Queries() {        
        initComponents();
        feedback_table();

        // center the form
        this.setLocationRelativeTo(this);
        
        Thread t = new Thread(this);
        t.start();
        
        GoBack.setVisible(false);
        
        // displaying users info
        sideBarFname.setText(LecturerCredentials.fullname);
        sideBarOperator.setText(LecturerCredentials.operator_id);  
        topBarSerialNo.setText(LecturerCredentials.serial_no);
    }
    
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryLogout;
    PreparedStatement sqlSubmitQuery;
    PreparedStatement sqlSubmitComment;
    PreparedStatement sqlQueryResolved;
    
    ResultSet res;
    Connection conn;
    
    DefaultTableModel defaulttbl_1_feedback;
    DefaultTableModel defaulttbl_2_view;
    DefaultTableModel defaulttbl_3_reply;
    DefaultTableModel defaulttbl_4_upload;
    DefaultTableModel defaulttbl_5_comment;
    DefaultTableModel defaulttbl_6_hide;
    DefaultTableModel defaulttbl_7_hide;
    
    private void feedback_table() {        
        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction");
            res = sqlQueryCheck.executeQuery();
            
            while(res.next()) {
                String feedbId     = res.getString("msg_id");
                String feedbStudId = res.getString("stud_identifier");
                String feedbFname  = res.getString("stud_fname");
                String feedbUnit   = res.getString("unit_name");
                String feedbLbl    = res.getString("msg_lbl");
                String feedbStatus = res.getString("msg_status");
                
                Object[] obj = {feedbId, feedbStudId, feedbFname, feedbUnit, feedbLbl, feedbStatus};
                
                defaulttbl_1_feedback = (DefaultTableModel)tbl_display.getModel();
                defaulttbl_1_feedback.addRow(obj);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topBarSerialNo = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        sideBarFname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtQueries = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        txtOverview = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        txtSettings = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        GoBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnQuery = new javax.swing.JButton();
        btnComment = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new rojeru_san.complementos.RSTableMetro();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        queryRetrieveStudName = new javax.swing.JLabel();
        queryRetrieveReg = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        queryRetrieveDateSent = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryRetrieveMsg = new javax.swing.JTextArea();
        queryRetrieveUnitName = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        btnGoToUpload = new javax.swing.JButton();
        btnGoToReply = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        replyToQueryMsg = new javax.swing.JTextArea();
        replyToRegQuery = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        replyToFnameQuery = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtReplyQuery = new javax.swing.JTextArea();
        jPanel42 = new javax.swing.JPanel();
        btnClearReply = new javax.swing.JButton();
        btnReplyQuery = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        replyToQueryMsg1 = new javax.swing.JTextArea();
        replyToRegQuery1 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        replyToFnameQuery1 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        btnBrowseDoc = new javax.swing.JButton();
        docNamePath = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        btnClearFilePath = new javax.swing.JButton();
        btnSubmitFile = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        commentRetrieveStudName = new javax.swing.JLabel();
        commentRetrieveReg = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        commentRetrieveDateSent = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        commentRetrieveMsg = new javax.swing.JTextArea();
        commentRetrieveUnitName = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        btnGoToReplyComment = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        replyToCommentMsg = new javax.swing.JTextArea();
        replyToRegComment = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        replyToFnameComment = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtReplyComment = new javax.swing.JTextArea();
        jPanel45 = new javax.swing.JPanel();
        btnClearReplyComment = new javax.swing.JButton();
        btnReplyComment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setText("Interaction Page");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 190, 30));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel5.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 17));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.windowBorder);
        jLabel8.setText("Serial No:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        topBarSerialNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel5.add(topBarSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 60, 100, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 17));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 600, 90));

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masomo");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Bora");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holder1.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 160, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });
        jPanel34.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jPanel34.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 150, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQueries.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtQueries.setForeground(new java.awt.Color(255, 255, 255));
        txtQueries.setText("Queries");
        txtQueries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtQueries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQueriesMouseClicked(evt);
            }
        });
        jPanel37.add(txtQueries, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/interact.png"))); // NOI18N
        jPanel37.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 150, 30));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOverview.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtOverview.setForeground(new java.awt.Color(255, 255, 255));
        txtOverview.setText("Overview");
        txtOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOverviewMouseClicked(evt);
            }
        });
        jPanel38.add(txtOverview, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/feedback.png"))); // NOI18N
        jPanel38.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 150, 30));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings.setText("Settings");
        txtSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettingsMouseClicked(evt);
            }
        });
        jPanel39.add(txtSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel39.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 150, 30));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Logout");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        jPanel32.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 460, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GoBack.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        GoBack.setText("Back");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });
        jPanel6.add(GoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 100, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setText("Show All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        btnQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnQuery.setText("View");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        jPanel6.add(btnQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 30));

        btnComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnComment.setText("View");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });
        jPanel6.add(btnComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 560, 32));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# ", "Reg No", "Full Name", "Unit", "Label", "Status"
            }
        ));
        tbl_display.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbl_display.setColorBordeHead(new java.awt.Color(0, 112, 192));
        tbl_display.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_display.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_display.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_display.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_display.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_display.setFuenteHead(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_display.setGrosorBordeFilas(0);
        tbl_display.setGrosorBordeHead(0);
        tbl_display.setMultipleSeleccion(false);
        tbl_display.setRowHeight(25);
        tbl_display.setShowHorizontalLines(false);
        tbl_display.setShowVerticalLines(false);
        tbl_display.getTableHeader().setReorderingAllowed(false);
        tbl_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_display);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("View this Query");

        jPanel60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel60.setOpaque(false);
        jPanel60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Student Information");
        jPanel60.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel67.setForeground(java.awt.SystemColor.windowBorder);
        jLabel67.setText("Reg No:");
        jPanel60.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel68.setForeground(java.awt.SystemColor.windowBorder);
        jLabel68.setText("Full name:");
        jPanel60.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        queryRetrieveStudName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel60.add(queryRetrieveStudName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 240, 20));

        queryRetrieveReg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel60.add(queryRetrieveReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 20));

        jPanel61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel61.setOpaque(false);
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setText("Query Information");
        jPanel61.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel72.setForeground(java.awt.SystemColor.windowBorder);
        jLabel72.setText("Was sent on:");
        jPanel61.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel73.setForeground(java.awt.SystemColor.windowBorder);
        jLabel73.setText("Body:");
        jPanel61.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        queryRetrieveDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel61.add(queryRetrieveDateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 16));

        queryRetrieveMsg.setEditable(false);
        queryRetrieveMsg.setColumns(20);
        queryRetrieveMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        queryRetrieveMsg.setLineWrap(true);
        queryRetrieveMsg.setRows(5);
        queryRetrieveMsg.setBorder(null);
        jScrollPane4.setViewportView(queryRetrieveMsg);

        jPanel61.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 100));
        jPanel61.add(queryRetrieveUnitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 260, 16));

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setOpaque(false);
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoToUpload.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToUpload.setText("Upload File");
        btnGoToUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToUploadActionPerformed(evt);
            }
        });
        jPanel41.add(btnGoToUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1, 110, 28));

        btnGoToReply.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToReply.setText("Reply Back");
        btnGoToReply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToReplyActionPerformed(evt);
            }
        });
        jPanel41.add(btnGoToReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 28));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Reply to this Query");

        jPanel62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel62.setOpaque(false);
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setText("Query Information");
        jPanel62.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel75.setForeground(java.awt.SystemColor.windowBorder);
        jLabel75.setText("Reg No: ");
        jPanel62.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        replyToQueryMsg.setEditable(false);
        replyToQueryMsg.setColumns(20);
        replyToQueryMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        replyToQueryMsg.setLineWrap(true);
        replyToQueryMsg.setRows(5);
        replyToQueryMsg.setBorder(null);
        jScrollPane5.setViewportView(replyToQueryMsg);

        jPanel62.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 70));
        jPanel62.add(replyToRegQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 16));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel77.setForeground(java.awt.SystemColor.windowBorder);
        jLabel77.setText("Student Name:");
        jPanel62.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        jPanel62.add(replyToFnameQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 16));

        jPanel63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel63.setOpaque(false);
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel78.setText("Reply Section");
        jPanel63.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        txtReplyQuery.setColumns(20);
        txtReplyQuery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtReplyQuery.setForeground(java.awt.Color.gray);
        txtReplyQuery.setLineWrap(true);
        txtReplyQuery.setRows(5);
        txtReplyQuery.setText("start typing ...");
        txtReplyQuery.setBorder(null);
        txtReplyQuery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReplyQueryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReplyQueryFocusLost(evt);
            }
        });
        jScrollPane6.setViewportView(txtReplyQuery);

        jPanel63.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 80));

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setOpaque(false);
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClearReply.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearReply.setText("Clear");
        btnClearReply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearReplyActionPerformed(evt);
            }
        });
        jPanel42.add(btnClearReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1, 110, 28));

        btnReplyQuery.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnReplyQuery.setText("Submit");
        btnReplyQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReplyQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyQueryActionPerformed(evt);
            }
        });
        jPanel42.add(btnReplyQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 28));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel62, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel62, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel63, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 390));

        jTabbedPane1.addTab("tab3", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Reply to this Query");

        jPanel64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel64.setOpaque(false);
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel79.setText("Query Information");
        jPanel64.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel81.setForeground(java.awt.SystemColor.windowBorder);
        jLabel81.setText("Reg No: ");
        jPanel64.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel82.setForeground(java.awt.SystemColor.windowBorder);
        jLabel82.setText("Body:");
        jPanel64.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        replyToQueryMsg1.setEditable(false);
        replyToQueryMsg1.setColumns(20);
        replyToQueryMsg1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        replyToQueryMsg1.setLineWrap(true);
        replyToQueryMsg1.setRows(5);
        replyToQueryMsg1.setBorder(null);
        jScrollPane7.setViewportView(replyToQueryMsg1);

        jPanel64.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 70));
        jPanel64.add(replyToRegQuery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 16));

        jLabel83.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel83.setForeground(java.awt.SystemColor.windowBorder);
        jLabel83.setText("Student Name:");
        jPanel64.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        jPanel64.add(replyToFnameQuery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 16));

        jPanel65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel65.setOpaque(false);
        jPanel65.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel84.setText("Upload Section");
        jPanel65.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        btnBrowseDoc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBrowseDoc.setText("Browse  Document");
        btnBrowseDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowseDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseDocActionPerformed(evt);
            }
        });
        jPanel65.add(btnBrowseDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 180, 30));

        docNamePath.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jPanel65.add(docNamePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 510, 16));

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setOpaque(false);
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClearFilePath.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearFilePath.setText("Clear");
        btnClearFilePath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilePathActionPerformed(evt);
            }
        });
        jPanel43.add(btnClearFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 28));

        btnSubmitFile.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSubmitFile.setText("Submit");
        btnSubmitFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFileActionPerformed(evt);
            }
        });
        jPanel43.add(btnSubmitFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 28));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jPanel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel64, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel65, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab4", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("View this Comment");

        jPanel66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel66.setOpaque(false);
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setText("Student Information");
        jPanel66.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel70.setForeground(java.awt.SystemColor.windowBorder);
        jLabel70.setText("Reg No:");
        jPanel66.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel85.setForeground(java.awt.SystemColor.windowBorder);
        jLabel85.setText("Full name:");
        jPanel66.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        commentRetrieveStudName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel66.add(commentRetrieveStudName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 240, 20));

        commentRetrieveReg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel66.add(commentRetrieveReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 20));

        jPanel67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel67.setOpaque(false);
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel86.setText("Comment Information");
        jPanel67.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel87.setForeground(java.awt.SystemColor.windowBorder);
        jLabel87.setText("Was sent on:");
        jPanel67.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel88.setForeground(java.awt.SystemColor.windowBorder);
        jLabel88.setText("Body:");
        jPanel67.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        commentRetrieveDateSent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel67.add(commentRetrieveDateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 16));

        commentRetrieveMsg.setEditable(false);
        commentRetrieveMsg.setColumns(20);
        commentRetrieveMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        commentRetrieveMsg.setLineWrap(true);
        commentRetrieveMsg.setRows(5);
        commentRetrieveMsg.setBorder(null);
        jScrollPane8.setViewportView(commentRetrieveMsg);

        jPanel67.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 100));
        jPanel67.add(commentRetrieveUnitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 260, 16));

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setOpaque(false);
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoToReplyComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToReplyComment.setText("Reply Back");
        btnGoToReplyComment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToReplyComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToReplyCommentActionPerformed(evt);
            }
        });
        jPanel44.add(btnGoToReplyComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 28));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel67, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel67, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab5", jPanel12);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Reply to this Comment");

        jPanel68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel68.setOpaque(false);
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setText("Comment Information");
        jPanel68.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel80.setForeground(java.awt.SystemColor.windowBorder);
        jLabel80.setText("Reg No: ");
        jPanel68.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        replyToCommentMsg.setEditable(false);
        replyToCommentMsg.setColumns(20);
        replyToCommentMsg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        replyToCommentMsg.setLineWrap(true);
        replyToCommentMsg.setRows(5);
        replyToCommentMsg.setBorder(null);
        jScrollPane9.setViewportView(replyToCommentMsg);

        jPanel68.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 70));
        jPanel68.add(replyToRegComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 16));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel89.setForeground(java.awt.SystemColor.windowBorder);
        jLabel89.setText("Student Name:");
        jPanel68.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        jPanel68.add(replyToFnameComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 16));

        jPanel69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel69.setOpaque(false);
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel90.setText("Reply Section");
        jPanel69.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        txtReplyComment.setColumns(20);
        txtReplyComment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtReplyComment.setForeground(java.awt.Color.gray);
        txtReplyComment.setLineWrap(true);
        txtReplyComment.setRows(5);
        txtReplyComment.setText("start typing ...");
        txtReplyComment.setBorder(null);
        txtReplyComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReplyCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReplyCommentFocusLost(evt);
            }
        });
        jScrollPane10.setViewportView(txtReplyComment);

        jPanel69.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 490, 80));

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setOpaque(false);
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClearReplyComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearReplyComment.setText("Clear");
        btnClearReplyComment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearReplyComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearReplyCommentActionPerformed(evt);
            }
        });
        jPanel45.add(btnClearReplyComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1, 110, 28));

        btnReplyComment.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnReplyComment.setText("Submit");
        btnReplyComment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReplyComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyCommentActionPerformed(evt);
            }
        });
        jPanel45.add(btnReplyComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 28));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel68, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel69, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 390));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab6", jPanel19);

        jPanel7.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 560, 430));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 560, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtQueriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQueriesMouseClicked
        // Go to Queries 
        Page3_Queries startInt = new Page3_Queries();
        this.dispose();
        startInt.setVisible(true);
    }//GEN-LAST:event_txtQueriesMouseClicked

    private void txtOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOverviewMouseClicked
        // Go to overview
        Page4_Overview overVW = new Page4_Overview();
        this.dispose();
        overVW.setVisible(true);
    }//GEN-LAST:event_txtOverviewMouseClicked

    private void txtSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettingsMouseClicked
        // Go to settings
        Page5_Settings pwd = new Page5_Settings();
        this.dispose();
        pwd.setVisible(true);
    }//GEN-LAST:event_txtSettingsMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // operation for login out
        String serialNo = topBarSerialNo.getText();

        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_lecturers SET status='Offline' WHERE serial_no=? ");
            sqlQueryLogout.setString(1, serialNo);

            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_Login login = new Page1_Login();

                // include logout function
                LecturerPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page5_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        GoBack.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        GoBack.setVisible(true);
        
        String cleared = "Yes";
        String upload  = null;
        defaulttbl_6_hide = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_6_hide.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String doubtCleared = res.getString("doubt_cleared");
                
                if (doubtCleared.equals(cleared)){
                    btnGoToReply.setVisible(false);
                } 
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        GoBack.setVisible(true);
        
        String cleared = "Yes";
        defaulttbl_7_hide = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_7_hide.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String doubtCleared = res.getString("doubt_cleared");
                
                if (doubtCleared.equals(cleared)){
                    btnGoToReplyComment.setVisible(false);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCommentActionPerformed

    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        GoBack.setVisible(false);
    }//GEN-LAST:event_GoBackActionPerformed

    private void tbl_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_displayMouseClicked
        String lblQuery = "Query";
        String lblComment = "Comment";

        defaulttbl_2_view = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_2_view.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispStudId  = res.getString("stud_identifier");
                String dispFname   = res.getString("stud_fname");
                String dispDate    = res.getString("date_sent");
                String dispUnit    = res.getString("unit_name");
                String dispLbl     = res.getString("msg_lbl");
                String dispContent = res.getString("msg_content");

                if (dispLbl.equals(lblQuery)){
                    btnQuery.setVisible(true);
                    btnComment.setVisible(false);

                    queryRetrieveReg.setText(dispStudId);
                    queryRetrieveStudName.setText(dispFname);
                    queryRetrieveDateSent.setText(dispDate);
                    queryRetrieveUnitName.setText(dispUnit);
                    queryRetrieveMsg.setText(dispContent);
                }
                else if (dispLbl.equals(lblComment)){
                    btnQuery.setVisible(false);
                    btnComment.setVisible(true);

                    commentRetrieveReg.setText(dispStudId);
                    commentRetrieveStudName.setText(dispFname);
                    commentRetrieveDateSent.setText(dispDate);
                    commentRetrieveUnitName.setText(dispUnit);
                    commentRetrieveMsg.setText(dispContent);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_displayMouseClicked

    private void btnGoToUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToUploadActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        GoBack.setVisible(true);
        
        defaulttbl_4_upload = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_4_upload.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispStudId  = res.getString("stud_identifier");
                String dispFname   = res.getString("stud_fname");
                String dispContent = res.getString("msg_content");

                replyToRegQuery1.setText(dispStudId);
                replyToFnameQuery1.setText(dispFname);
                replyToQueryMsg1.setText(dispContent);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGoToUploadActionPerformed

    private void btnGoToReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToReplyActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        GoBack.setVisible(true);
        
        defaulttbl_3_reply = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_3_reply.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispStudId  = res.getString("stud_identifier");
                String dispFname   = res.getString("stud_fname");
                String dispContent = res.getString("msg_content");

                replyToRegQuery.setText(dispStudId);
                replyToFnameQuery.setText(dispFname);
                replyToQueryMsg.setText(dispContent);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGoToReplyActionPerformed

    private void txtReplyQueryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReplyQueryFocusGained
        // operation that occur when this field is clicked
        if(txtReplyQuery.getText().trim().toLowerCase().equals("start typing ...")){
            txtReplyQuery.setText("");
            txtReplyQuery.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtReplyQueryFocusGained

    private void txtReplyQueryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReplyQueryFocusLost
        // operation that occur when this field is not clicked
        if(txtReplyQuery.getText().trim().equals("") || txtReplyQuery.getText().trim().equals("start typing ...")){
            txtReplyQuery.setText("start typing ...");
            txtReplyQuery.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtReplyQueryFocusLost

    private void btnClearReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReplyActionPerformed
        // clearing the form body
        txtReplyQuery.setText("");
        if(txtReplyQuery.getText().trim().equals("") || txtReplyQuery.getText().trim().equals("start typing ...")){
            txtReplyQuery.setText("start typing ...");
            txtReplyQuery.setForeground(Color.gray);
        }
    }//GEN-LAST:event_btnClearReplyActionPerformed

    private void btnReplyQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyQueryActionPerformed
        // operation for replying a query    
        // comparison variables
        String studId       = replyToRegQuery.getText();    
        String lecId        = topBarSerialNo.getText(); 
        String unitName     = queryRetrieveUnitName.getText();
        String queryContent = replyToQueryMsg.getText(); 
        
        // variables to be inserted in the database
        String msgStatus  = "Resolved";
        String msgContent = txtReplyQuery.getText();
        String date_sent  = txtDate.getText();   
        String cleared    = "Yes";            
        
        // checking if any field is empty before submitting the form
        if(msgContent.trim().equals("") || msgContent.trim().equals("start typing ...")){
            JOptionPane.showMessageDialog(null, "Cannot submit an Empty Form", "Form Submission Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                conn = DBConnection.setConnection();
                sqlSubmitQuery = conn.prepareStatement("update tbl_interaction set msg_status=?, replied_msg=?, date_replied=?, doubt_cleared=? where stud_identifier=? and lec_identifier=? and unit_name=? and msg_content=?");
                sqlSubmitQuery.setString(1, msgStatus);
                sqlSubmitQuery.setString(2, msgContent);
                sqlSubmitQuery.setString(3, date_sent);
                sqlSubmitQuery.setString(4, cleared);
                sqlSubmitQuery.setString(5, studId);
                sqlSubmitQuery.setString(6, lecId);
                sqlSubmitQuery.setString(7, unitName);
                sqlSubmitQuery.setString(8, queryContent);
                
                //if the record is inserted successfully the state of executeUpdate() will be 1
                if (sqlSubmitQuery.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "The query was successfully resolved.");
                            
                    // redirect 
                    new Page4_Overview().setVisible(true);
                    this.dispose();

                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnReplyQueryActionPerformed

    private void btnBrowseDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseDocActionPerformed
        // operation for browsing a document
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));        
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Allowed File is PDF","pdf");  // file extension
        fileChooser.addChoosableFileFilter(extension);
        int load = fileChooser.showOpenDialog(null);
        
        // check if the user has selected an image
        if(load == fileChooser.APPROVE_OPTION) {
            File docName = fileChooser.getSelectedFile();
            String path  = docName.getAbsolutePath();
            docNamePath.setText(path);
        }
    }//GEN-LAST:event_btnBrowseDocActionPerformed

    private void btnClearFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilePathActionPerformed
        // operation for clearing a file path
        docNamePath.setText("");
    }//GEN-LAST:event_btnClearFilePathActionPerformed

    private void btnSubmitFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFileActionPerformed
        // operation for submitting a document
        // comparison variables
        String studId       = replyToRegQuery1.getText();    
        String lecId        = topBarSerialNo.getText(); 
        String unitName     = queryRetrieveUnitName.getText();
        String queryContent = replyToQueryMsg1.getText(); 
        
        // variables to be inserted in the database
        String msgStatus = "Resolved";
        String path      = docNamePath.getText();
        File docName     = new File(path);
        String date_sent = txtDate.getText();   
        String cleared   = "Yes";  
        
        try {
            InputStream inputS = new FileInputStream(docName);
            
            conn = DBConnection.setConnection();
            sqlSubmitQuery = conn.prepareStatement("update tbl_interaction set msg_status=?, link_doc=?, document=?, date_replied=?, doubt_cleared=? where stud_identifier=? and lec_identifier=? and unit_name=? and msg_content=?");
            sqlSubmitQuery.setString(1, msgStatus);
            sqlSubmitQuery.setString(2, path);
            sqlSubmitQuery.setBlob(3, inputS);
            sqlSubmitQuery.setString(4, date_sent);
            sqlSubmitQuery.setString(5, cleared);
            sqlSubmitQuery.setString(6, studId);
            sqlSubmitQuery.setString(7, lecId);
            sqlSubmitQuery.setString(8, unitName);
            sqlSubmitQuery.setString(9, queryContent);

            //if the record is inserted successfully the state of executeUpdate() will be 1
            if (sqlSubmitQuery.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "The query was successfully resolved.");

                // redirect 
                new Page4_Overview().setVisible(true);
                this.dispose();

                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitFileActionPerformed

    private void btnGoToReplyCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToReplyCommentActionPerformed
        jTabbedPane1.setSelectedIndex(5);
        GoBack.setVisible(true);
        
        defaulttbl_5_comment = (DefaultTableModel)tbl_display.getModel();
        int selectIndex = tbl_display.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_5_comment.getValueAt(selectIndex, 0).toString());

        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_interaction where msg_id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                String dispStudId  = res.getString("stud_identifier");
                String dispFname   = res.getString("stud_fname");
                String dispContent = res.getString("msg_content");

                replyToRegComment.setText(dispStudId);
                replyToFnameComment.setText(dispFname);
                replyToCommentMsg.setText(dispContent);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGoToReplyCommentActionPerformed

    private void txtReplyCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReplyCommentFocusGained
        // operation that occur when this field is clicked
        if(txtReplyComment.getText().trim().toLowerCase().equals("start typing ...")){
            txtReplyComment.setText("");
            txtReplyComment.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtReplyCommentFocusGained

    private void txtReplyCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReplyCommentFocusLost
        // operation that occur when this field is not clicked
        if(txtReplyComment.getText().trim().equals("") || txtReplyComment.getText().trim().equals("start typing ...")){
            txtReplyComment.setText("start typing ...");
            txtReplyComment.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtReplyCommentFocusLost

    private void btnClearReplyCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReplyCommentActionPerformed
        // clearing the form body
        txtReplyComment.setText("");
        if(txtReplyComment.getText().trim().equals("") || txtReplyComment.getText().trim().equals("start typing ...")){
            txtReplyComment.setText("start typing ...");
            txtReplyComment.setForeground(Color.gray);
        }
    }//GEN-LAST:event_btnClearReplyCommentActionPerformed

    private void btnReplyCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyCommentActionPerformed
        // operation for replying a query
        // comparison variables
        String studId       = replyToRegComment.getText();    
        String lecId        = topBarSerialNo.getText(); 
        String unitName     = commentRetrieveUnitName.getText();
        String queryContent = replyToCommentMsg.getText(); 
        
        // variables to be inserted in the database
        String msgStatus  = "Replied";
        String msgContent = txtReplyComment.getText();
        String date_sent  = txtDate.getText();   
        String cleared    = "Yes";           
        
        // checking if any field is empty before submitting the form
        if(msgContent.trim().equals("") || msgContent.trim().equals("start typing ...")){
            JOptionPane.showMessageDialog(null, "Cannot submit an Empty Form", "Form Submission Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                conn = DBConnection.setConnection();
                sqlSubmitQuery = conn.prepareStatement("update tbl_interaction set msg_status=?, replied_msg=?, date_replied=?, doubt_cleared=? where stud_identifier=? and lec_identifier=? and unit_name=? and msg_content=?");
                sqlSubmitQuery.setString(1, msgStatus);
                sqlSubmitQuery.setString(2, msgContent);
                sqlSubmitQuery.setString(3, date_sent);
                sqlSubmitQuery.setString(4, cleared);
                sqlSubmitQuery.setString(5, studId);
                sqlSubmitQuery.setString(6, lecId);
                sqlSubmitQuery.setString(7, unitName);
                sqlSubmitQuery.setString(8, queryContent);
                
                //if the record is inserted successfully the state of executeUpdate() will be 1
                if (sqlSubmitQuery.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "The Comment was successfully replied.");
                            
                    // redirect 
                    new Page4_Overview().setVisible(true);
                    this.dispose();

                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Queries.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnReplyCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3_Queries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3_Queries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3_Queries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3_Queries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3_Queries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBack;
    private javax.swing.JButton btnBrowseDoc;
    private javax.swing.JButton btnClearFilePath;
    private javax.swing.JButton btnClearReply;
    private javax.swing.JButton btnClearReplyComment;
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnGoToReply;
    private javax.swing.JButton btnGoToReplyComment;
    private javax.swing.JButton btnGoToUpload;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnReplyComment;
    private javax.swing.JButton btnReplyQuery;
    private javax.swing.JButton btnSubmitFile;
    private javax.swing.JLabel commentRetrieveDateSent;
    private javax.swing.JTextArea commentRetrieveMsg;
    private javax.swing.JLabel commentRetrieveReg;
    private javax.swing.JLabel commentRetrieveStudName;
    private javax.swing.JLabel commentRetrieveUnitName;
    private javax.swing.JLabel docNamePath;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel queryRetrieveDateSent;
    private javax.swing.JTextArea queryRetrieveMsg;
    private javax.swing.JLabel queryRetrieveReg;
    private javax.swing.JLabel queryRetrieveStudName;
    private javax.swing.JLabel queryRetrieveUnitName;
    private javax.swing.JTextArea replyToCommentMsg;
    private javax.swing.JLabel replyToFnameComment;
    private javax.swing.JLabel replyToFnameQuery;
    private javax.swing.JLabel replyToFnameQuery1;
    private javax.swing.JTextArea replyToQueryMsg;
    private javax.swing.JTextArea replyToQueryMsg1;
    private javax.swing.JLabel replyToRegComment;
    private javax.swing.JLabel replyToRegQuery;
    private javax.swing.JLabel replyToRegQuery1;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private rojeru_san.complementos.RSTableMetro tbl_display;
    private javax.swing.JLabel topBarSerialNo;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private javax.swing.JLabel txtOverview;
    private javax.swing.JLabel txtQueries;
    private javax.swing.JTextArea txtReplyComment;
    private javax.swing.JTextArea txtReplyQuery;
    private javax.swing.JLabel txtSettings;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
