/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForAdmin;

import DB.AdminCredentials;
import DB.AdminPageLogout;
import DB.Admin_AccessMG_Credentials;
import DB.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojeru_san.complementos.RSScrollBar;

/**
 *
 * @author JoeAlpha
 */
public class Page3_Manager extends javax.swing.JFrame implements Runnable {
    SimpleDateFormat timeFormat;// setting variable for time Format
    SimpleDateFormat dayFormat;// setting variable for day Format
    SimpleDateFormat dateFormat;// setting variable for date Format
    String time; // setting variable for current time
    String day; // setting variable for day
    String date; // setting variable for date

    /**
     * Creates new form Page2_Dashboard
     */
    public Page3_Manager() {        
        initComponents();
        managers_table();

        // center the form
        this.setLocationRelativeTo(this);
        jScrollPane1.getVerticalScrollBar().setUI(new RSScrollBar());
        
        Thread t = new Thread(this);
        t.start();
        
        btnViewMg.setVisible(false);
        btnDelMg.setVisible(false);
        
        // creating button group for gender radio buttons
        ButtonGroup bgGroup = new ButtonGroup();
        bgGroup.add(btnMale);
        bgGroup.add(btnFemale);
        
        // displaying users info
        sideBarFname.setText(AdminCredentials.fullname);
        sideBarOperator.setText(AdminCredentials.operator_id); 
        topBarSerialNo.setText(AdminCredentials.serial_no);
    }
    
    
    // universal variables
    SimpleDateFormat dateofbirth; 
    
    PreparedStatement sqlQueryCheck;
    PreparedStatement sqlQueryInsert;
    PreparedStatement sqlQueryLogout;
    ResultSet res;
    Connection conn;
    
    DefaultTableModel defaulttbl_1_query;
    DefaultTableModel defaulttbl_2_view;
    DefaultTableModel defaulttbl_3_delete;
    
    
    private void managers_table() {
        try {
            conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_managers");
            res = sqlQueryCheck.executeQuery();
            
            while(res.next()) {
                String mgId     = res.getString("id");
                String mgSerial = res.getString("serial_no");
                String mgFname  = res.getString("fullname");
                String mgPhone  = "0"+res.getString("phone");
                String mgGender = res.getString("gender");
                
                Object[] obj = {mgId, mgSerial, mgFname, mgPhone, mgGender};
                
                defaulttbl_1_query = (DefaultTableModel)tbl_managers.getModel();
                defaulttbl_1_query.addRow(obj);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sideBarOperator = new javax.swing.JLabel();
        sideBarFname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        txtManager = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        txtLecturer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        txtStudent = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        txtSettings = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        txtSettings1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topBarSerialNo = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        btnShowAllMg = new javax.swing.JButton();
        btnGoToAddMg = new javax.swing.JButton();
        btnDelMg = new javax.swing.JButton();
        btnViewMg = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_managers = new rojeru_san.complementos.RSTableMetro();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mgSerial = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mgDob = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        mgIdNo = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        mgFname = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        mgGender = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        mgEmail = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        mgPhone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        serialLine = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        errorReg = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        fnameLine = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        errorFname = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        idnoLine = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtIdNo = new javax.swing.JTextField();
        errorId = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        emailLine = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        errorEmail = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        passwordLine = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        errorPassword = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        phoneLine = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        errorPhone = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        jPanel52 = new javax.swing.JPanel();
        btnFemale = new javax.swing.JRadioButton();
        btnMale = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        btnCreateAcc = new javax.swing.JButton();
        btnResetAccForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Masomo");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Bora");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 50, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holder1.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 40, 40));

        sideBarOperator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarOperator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 21, 130, 20));

        sideBarFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sideBarFname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(sideBarFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 130, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 160, 1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 60));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setOpaque(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
        });
        jPanel34.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jPanel34.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, 150, 30));

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setOpaque(false);
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtManager.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtManager.setForeground(new java.awt.Color(255, 255, 255));
        txtManager.setText("Managers");
        txtManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtManagerMouseClicked(evt);
            }
        });
        jPanel36.add(txtManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Manager.png"))); // NOI18N
        jPanel36.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 150, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLecturer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtLecturer.setForeground(new java.awt.Color(255, 255, 255));
        txtLecturer.setText("Lecturer");
        txtLecturer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLecturerMouseClicked(evt);
            }
        });
        jPanel37.add(txtLecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lecturer.png"))); // NOI18N
        jPanel37.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 150, 30));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStudent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtStudent.setForeground(new java.awt.Color(255, 255, 255));
        txtStudent.setText("Students");
        txtStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentMouseClicked(evt);
            }
        });
        jPanel38.add(txtStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Student.png"))); // NOI18N
        jPanel38.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 150, 30));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings.setText("Settings");
        txtSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettingsMouseClicked(evt);
            }
        });
        jPanel39.add(txtSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel39.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 350, 150, 30));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Logout");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        jPanel32.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 480, 150, 30));

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setOpaque(false);
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSettings1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtSettings1.setForeground(new java.awt.Color(255, 255, 255));
        txtSettings1.setText("Report");
        txtSettings1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSettings1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSettings1MouseClicked(evt);
            }
        });
        jPanel42.add(txtSettings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        jPanel42.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 30, 26));

        jPanel2.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 405, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setText("View Managers");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.windowBorder);
        jLabel8.setText("Serial No:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        topBarSerialNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jPanel5.add(topBarSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 60, 100, 17));

        txtTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jPanel5.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 17));

        txtDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 17));

        txtDay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        txtDay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 100, 17));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1, 600, 90));

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShowAllMg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAllMg.setText("Show All");
        btnShowAllMg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAllMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllMgActionPerformed(evt);
            }
        });
        jPanel40.add(btnShowAllMg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        btnGoToAddMg.setBackground(java.awt.SystemColor.textHighlight);
        btnGoToAddMg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoToAddMg.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToAddMg.setText("Add");
        btnGoToAddMg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoToAddMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToAddMgActionPerformed(evt);
            }
        });
        jPanel40.add(btnGoToAddMg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 30));

        btnDelMg.setBackground(java.awt.Color.red);
        btnDelMg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDelMg.setForeground(new java.awt.Color(255, 255, 255));
        btnDelMg.setText("Delete");
        btnDelMg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMgActionPerformed(evt);
            }
        });
        jPanel40.add(btnDelMg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 30));

        btnViewMg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnViewMg.setText("View");
        btnViewMg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMgActionPerformed(evt);
            }
        });
        jPanel40.add(btnViewMg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 70, 30));

        jPanel1.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 560, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tbl_managers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# ", "Serial", "Full Name", "Phone", "Gender"
            }
        ));
        tbl_managers.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbl_managers.setColorBordeHead(new java.awt.Color(0, 112, 192));
        tbl_managers.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_managers.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_managers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_managers.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_managers.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_managers.setFuenteHead(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_managers.setGrosorBordeFilas(0);
        tbl_managers.setGrosorBordeHead(0);
        tbl_managers.setMultipleSeleccion(false);
        tbl_managers.setRowHeight(25);
        tbl_managers.setShowHorizontalLines(false);
        tbl_managers.setShowVerticalLines(false);
        tbl_managers.getTableHeader().setReorderingAllowed(false);
        tbl_managers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_managersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_managers);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("View Manager Info");

        jPanel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel45.setOpaque(false);
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.windowBorder);
        jLabel9.setText("Serial No:");
        jPanel45.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        mgSerial.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(mgSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.SystemColor.windowBorder);
        jLabel19.setText("Date of Birth:");
        jPanel45.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        mgDob.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(mgDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 20));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel50.setForeground(java.awt.SystemColor.windowBorder);
        jLabel50.setText("ID No:");
        jPanel45.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        mgIdNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(mgIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel52.setForeground(java.awt.SystemColor.windowBorder);
        jLabel52.setText("Full name:");
        jPanel45.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        mgFname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(mgFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 320, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel54.setForeground(java.awt.SystemColor.windowBorder);
        jLabel54.setText("Gender:");
        jPanel45.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        mgGender.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel45.add(mgGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 150, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Basic Infomartion");
        jPanel45.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jPanel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel46.setOpaque(false);
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(java.awt.SystemColor.windowBorder);
        jLabel18.setText("Email Address:");
        jPanel46.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        mgEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel46.add(mgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 20));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setForeground(java.awt.SystemColor.windowBorder);
        jLabel40.setText("Phone number:");
        jPanel46.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        mgPhone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel46.add(mgPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Contact Infomartion");
        jPanel46.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel43.setOpaque(false);
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialLine.setBackground(java.awt.Color.darkGray);
        serialLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel43.add(serialLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 225, 1));
        jPanel43.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtSerialNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSerialNo.setForeground(java.awt.Color.gray);
        txtSerialNo.setText("serial no.(mg1234567890)");
        txtSerialNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSerialNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSerialNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSerialNoFocusLost(evt);
            }
        });
        txtSerialNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerialNoKeyReleased(evt);
            }
        });
        jPanel43.add(txtSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorReg.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorReg.setForeground(java.awt.Color.red);
        jPanel43.add(errorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 226, 19));

        jPanel44.setOpaque(false);
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fnameLine.setBackground(java.awt.Color.darkGray);
        fnameLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel44.add(fnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 225, 1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel44.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtFullname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFullname.setForeground(java.awt.Color.gray);
        txtFullname.setText("fullname");
        txtFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullnameFocusLost(evt);
            }
        });
        txtFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameKeyReleased(evt);
            }
        });
        jPanel44.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorFname.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorFname.setForeground(java.awt.Color.red);
        jPanel44.add(errorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 230, 19));

        jPanel47.setOpaque(false);
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idnoLine.setBackground(java.awt.Color.darkGray);
        idnoLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel47.add(idnoLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 225, 1));
        jPanel47.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtIdNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdNo.setForeground(java.awt.Color.gray);
        txtIdNo.setText("id no. (123456789)");
        txtIdNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIdNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdNoFocusLost(evt);
            }
        });
        txtIdNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdNoKeyReleased(evt);
            }
        });
        jPanel47.add(txtIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorId.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorId.setForeground(java.awt.Color.red);
        jPanel47.add(errorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 226, 19));

        jPanel48.setOpaque(false);
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLine.setBackground(java.awt.Color.darkGray);
        emailLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel48.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 225, 1));
        jPanel48.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel48.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorEmail.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorEmail.setForeground(java.awt.Color.red);
        jPanel48.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 226, 19));

        jPanel49.setOpaque(false);
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordLine.setBackground(java.awt.Color.darkGray);
        passwordLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel49.add(passwordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 225, 1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel49.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.setText("yourpassword");
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel49.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorPassword.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorPassword.setForeground(java.awt.Color.red);
        jPanel49.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 250, 19));

        jPanel50.setOpaque(false);
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phoneLine.setBackground(java.awt.Color.darkGray);
        phoneLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel50.add(phoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 225, 1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone.png"))); // NOI18N
        jPanel50.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 30, 27));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPhone.setForeground(java.awt.Color.gray);
        txtPhone.setText("07xxxxxxxx");
        txtPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel50.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 25));

        errorPhone.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        errorPhone.setForeground(java.awt.Color.red);
        jPanel50.add(errorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 226, 19));

        jPanel51.setOpaque(false);
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Date Of Birth:");
        jPanel51.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        txtDob.setToolTipText("Date of Birth"); // NOI18N
        txtDob.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDob.setOpaque(false);
        jPanel51.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 30));

        jPanel52.setOpaque(false);
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFemale.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.setOpaque(false);
        jPanel52.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        btnMale.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnMale.setSelected(true);
        btnMale.setText("Male");
        btnMale.setOpaque(false);
        jPanel52.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Create New Manager Account");

        jPanel41.setOpaque(false);
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateAcc.setBackground(java.awt.SystemColor.textHighlight);
        btnCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setText("Create");
        btnCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        jPanel41.add(btnCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 95, 28));

        btnResetAccForm.setText("Reset");
        btnResetAccForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetAccForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAccFormActionPerformed(evt);
            }
        });
        jPanel41.add(btnResetAccForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 95, 28));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel51, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", jPanel9);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 560, 430));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 560, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // Go to dashboard
        Page2_Dashboard dash = new Page2_Dashboard();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void txtManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManagerMouseClicked
        // Go to managers
        Page3_Manager mgtManage = new Page3_Manager();
        this.dispose();
        mgtManage.setVisible(true);
    }//GEN-LAST:event_txtManagerMouseClicked

    private void txtLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLecturerMouseClicked
        // Go to lecturer
        Page4_Lecturer mgtLec = new Page4_Lecturer();
        this.dispose();
        mgtLec.setVisible(true);
    }//GEN-LAST:event_txtLecturerMouseClicked

    private void txtStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentMouseClicked
        // Go to students
        Page5_Student mgtStud = new Page5_Student();
        this.dispose();
        mgtStud.setVisible(true);
    }//GEN-LAST:event_txtStudentMouseClicked

    private void txtSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettingsMouseClicked
        // Go to settings
        Page6_Settings pwd = new Page6_Settings();
        this.dispose();
        pwd.setVisible(true);
    }//GEN-LAST:event_txtSettingsMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // operation for login out
        String serialNo = topBarSerialNo.getText();
        
        try {
            conn = DBConnection.setConnection();
            sqlQueryLogout = conn.prepareStatement("update tbl_admin SET status='Offline' WHERE serial_no=? ");
            sqlQueryLogout.setString(1, serialNo);
            
            //if the logout is successfully the state of executeUpdate() will be 1
            if (sqlQueryLogout.executeUpdate() != 0) {
                // redirect to login
                Page1_Login login = new Page1_Login();

                // logout function
                AdminPageLogout.logMeOut(this, login);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel25MouseClicked

    private void btnShowAllMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllMgActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        btnViewMg.setVisible(false);
        btnDelMg.setVisible(false);
    }//GEN-LAST:event_btnShowAllMgActionPerformed

    private void btnGoToAddMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToAddMgActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        btnViewMg.setVisible(false);
        btnDelMg.setVisible(false);
    }//GEN-LAST:event_btnGoToAddMgActionPerformed

    private void btnDelMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMgActionPerformed
        // Operation for deleting manager account
        try {
            defaulttbl_3_delete = (DefaultTableModel)tbl_managers.getModel();
            int selectIndex = tbl_managers.getSelectedRow();

            int id = Integer.parseInt(defaulttbl_3_delete.getValueAt(selectIndex, 0).toString());

            // confirmation message
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete Account of this Manager", "Warnimg", JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION){
                try {
                    Connection conn = DBConnection.setConnection();
                    sqlQueryCheck = conn.prepareStatement("delete from tbl_managers where id=?");
                    sqlQueryCheck.setInt(1, id);
                    sqlQueryCheck.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Manager Account has been Deleted Successfully");

                    managers_table();

                    // refreshing the current page
                    new Page3_Manager().setVisible(true);
                    this.dispose();
                } catch (Exception ex) {
                    Logger.getLogger(Page3_Manager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No Account has been selected!", "Warnimg", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelMgActionPerformed

    private void btnViewMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMgActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnViewMgActionPerformed

    private void txtSerialNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerialNoFocusGained
        if(txtSerialNo.getText().trim().toLowerCase().equals("serial no.(mg1234567890)")){
            txtSerialNo.setText("");
            txtSerialNo.setForeground(Color.black);
            serialLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtSerialNoFocusGained

    private void txtSerialNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerialNoFocusLost
        if(txtSerialNo.getText().trim().equals("") || txtSerialNo.getText().trim().equals("serial no.(mg1234567890)")){
            txtSerialNo.setText("serial no.(mg1234567890)");
            txtSerialNo.setForeground(Color.gray);
            serialLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtSerialNoFocusLost

    private void txtSerialNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNoKeyReleased
        String PATTERN = "^[a-z A-Z 0-9/]{0,10}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtSerialNo.getText());

        if(!match.matches()) {
            errorReg.setText("Invalid Reg No!");
        } else {
            errorReg.setText(null);
        }
    }//GEN-LAST:event_txtSerialNoKeyReleased

    private void txtFullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullnameFocusGained
        if(txtFullname.getText().trim().toLowerCase().equals("fullname")){
            txtFullname.setText("");
            txtFullname.setForeground(Color.black);
            fnameLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtFullnameFocusGained

    private void txtFullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullnameFocusLost
        if(txtFullname.getText().trim().equals("") || txtFullname.getText().trim().equals("fullname")){
            txtFullname.setText("fullname");
            txtFullname.setForeground(Color.gray);
            fnameLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtFullnameFocusLost

    private void txtFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameKeyReleased
        String PATTERN = "^[a-z A-Z]{0,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtFullname.getText());

        if(!match.matches()) {
            errorFname.setText("Invalid fullname!");
        } else {
            errorFname.setText(null);
        }
    }//GEN-LAST:event_txtFullnameKeyReleased

    private void txtIdNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdNoFocusGained
        if(txtIdNo.getText().trim().toLowerCase().equals("id no. (123456789)")){
            txtIdNo.setText("");
            txtIdNo.setForeground(Color.black);
            idnoLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtIdNoFocusGained

    private void txtIdNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdNoFocusLost
        if(txtIdNo.getText().trim().equals("") || txtIdNo.getText().trim().equals("id no. (123456789)")){
            txtIdNo.setText("id no. (123456789)");
            txtIdNo.setForeground(Color.gray);
            idnoLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtIdNoFocusLost

    private void txtIdNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdNoKeyReleased
        String PATTERN = "^[0-9]{0,15}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtIdNo.getText());

        if(!match.matches()) {
            errorId.setText("Invalid ID Number!");
        } else {
            errorId.setText(null);
        }
    }//GEN-LAST:event_txtIdNoKeyReleased

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
            emailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            emailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // validating email field to ensure (@) and (.) symbol are not ommitted
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{1,10}[.][a-zA-Z0-9]{2,5}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtEmail.getText());

        if(!match.matches()) {
            errorEmail.setText("Invalid email address!");
        } else {
            errorEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(txtPassword.getText().trim().toLowerCase().equals("yourpassword")){
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
            passwordLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().trim().equals("") || txtPassword.getText().trim().equals("yourpassword")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            passwordLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPassword.getText());

        if(!match.matches()) {
            errorPassword.setText("Invalid Password/use atleast 10 characters or more!");
        } else {
            errorPassword.setText(null);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        if(txtPhone.getText().trim().toLowerCase().equals("07xxxxxxxx")){
            txtPhone.setText("");
            txtPhone.setForeground(Color.black);
            phoneLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        if(txtPhone.getText().trim().equals("") || txtPhone.getText().trim().equals("07xxxxxxxx")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            phoneLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        String PATTERN = "^[0-9]{0,10}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPhone.getText());

        if(!match.matches()) {
            errorPhone.setText("Invalid phonenumber!");
        } else {
            errorPhone.setText(null);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // operation of createing a new account
        String status   = "Offline";
        String operator = "Manager";
        String serial   = txtSerialNo.getText();
        String id_no    = txtIdNo.getText();
        String fullname = txtFullname.getText();
        String email    = txtEmail.getText();
        String phone    = txtPhone.getText();

        String gender   = "Male";
        if(btnFemale.isSelected()) { gender  = "Female"; }

        dateofbirth     = new SimpleDateFormat("YYYY-MM-dd");
        String dob      = dateofbirth.format(txtDob.getDate());

        String password = txtPassword.getText();

        // checking if any field is empty before submitting the form
        if(serial.trim().equals("") || serial.trim().equals("serial no.(mg1234567890)")){
            JOptionPane.showMessageDialog(null, "Serial Number is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(id_no.trim().equals("") || id_no.trim().equals("123456789")){
            JOptionPane.showMessageDialog(null, "Id Number is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(fullname.trim().equals("") || fullname.trim().equals("full name")){
            JOptionPane.showMessageDialog(null, "Fullname is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(email.trim().equals("") || email.trim().equals("someone@newmail.com")){
            JOptionPane.showMessageDialog(null, "Email Address is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(phone.trim().equals("") || phone.trim().equals("0700 000 000")){
            JOptionPane.showMessageDialog(null, "Phone Number is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(password.trim().equals("") || password.trim().equals("yourpassword")){
            JOptionPane.showMessageDialog(null, "Password is required!", "Please Fill in", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
            try {
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_managers where serial_no=? or id_no=? or email=? or phone=?");
                sqlQueryCheck.setString(1, serial);
                sqlQueryCheck.setString(2, id_no);
                sqlQueryCheck.setString(3, email);
                sqlQueryCheck.setString(4, phone);
                res = sqlQueryCheck.executeQuery();

                if(res.isBeforeFirst()) {
                    // if the credential already exist display error message
                    JOptionPane.showMessageDialog(this, "These Cridentials have been used by another manager", "Please use new Cridentials", JOptionPane.ERROR_MESSAGE);

                    // clearing neccessary fields to allow the admin to re-enter new Cridentials
                    txtSerialNo.setText("");
                    errorReg.setText(null);
                    if(txtSerialNo.getText().trim().equals("")){
                        txtSerialNo.setText("serial no.(mg1234567890)");
                        txtSerialNo.setForeground(Color.gray);
                        serialLine.setBackground(Color.black);
                    }

                    txtIdNo.setText("");
                    errorId.setText(null);
                    if(txtIdNo.getText().trim().equals("")){
                        txtIdNo.setText("id no. (123456789)");
                        txtIdNo.setForeground(Color.gray);
                        idnoLine.setBackground(Color.black);
                    }
        
                    txtEmail.setText("");
                    errorEmail.setText(null);
                    if(txtEmail.getText().trim().equals("")){
                        txtEmail.setText("someone@newmail.com");
                        txtEmail.setForeground(Color.gray);
                        emailLine.setBackground(Color.black);
                    }

                    txtPhone.setText("");
                    errorPhone.setText(null);
                    if(txtPhone.getText().trim().equals("")){
                        txtPhone.setText("07xxxxxxxx");
                        txtPhone.setForeground(Color.gray);
                        phoneLine.setBackground(Color.black);
                    }

                    txtSerialNo.requestFocus();
                    return;
                }else {
                    sqlQueryInsert = conn.prepareStatement("insert into tbl_managers (status,operator_id,serial_no,id_no,fullname,email,phone,gender,date_ofbirth,password) values (?,?,?,?,?,?,?,?,?,?) ");
                    sqlQueryInsert.setString(1, status);
                    sqlQueryInsert.setString(2, operator);
                    sqlQueryInsert.setString(3, serial);
                    sqlQueryInsert.setString(4, id_no);
                    sqlQueryInsert.setString(5, fullname);
                    sqlQueryInsert.setString(6, email);
                    sqlQueryInsert.setString(7, phone);
                    sqlQueryInsert.setString(8, gender);
                    sqlQueryInsert.setString(9, dob);
                    sqlQueryInsert.setString(10, password);

                    //if the record is inserted successfully the state of executeUpdate() will be 1
                    if (sqlQueryInsert.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "A New Manager Account has been created successfully.");

                        // clearing the form after successfully adding the new record in the database
                        txtSerialNo.setText("");
                        txtIdNo.setText("");
                        txtFullname.setText("");
                        txtEmail.setText("");
                        txtPhone.setText("");
                        txtDob.setDate(null);
                        txtPassword.setText("");

                        // redirect the user to login page
                        new Page3_Manager().setVisible(true);
                        this.dispose();

                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Manager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnResetAccFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAccFormActionPerformed
        // operation for reseting the form
        txtSerialNo.setText("");
        errorReg.setText(null);
        if(txtSerialNo.getText().trim().equals("")){
            txtSerialNo.setText("serial no.(mg1234567890)");
            txtSerialNo.setForeground(Color.gray);
            serialLine.setBackground(Color.black);
        }

        txtIdNo.setText("");
        errorId.setText(null);
        if(txtIdNo.getText().trim().equals("")){
            txtIdNo.setText("id no. (123456789)");
            txtIdNo.setForeground(Color.gray);
            idnoLine.setBackground(Color.black);
        }

        txtFullname.setText("");
        errorFname.setText(null);
        if(txtFullname.getText().trim().equals("")){
            txtFullname.setText("fullname");
            txtFullname.setForeground(Color.gray);
            fnameLine.setBackground(Color.black);
        }

        txtDob.setDate(null);

        txtEmail.setText("");
        errorEmail.setText(null);
        if(txtEmail.getText().trim().equals("")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            emailLine.setBackground(Color.black);
        }

        txtPhone.setText("");
        errorPhone.setText(null);
        if(txtPhone.getText().trim().equals("")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            phoneLine.setBackground(Color.black);
        }

        txtPassword.setText("");
        errorPassword.setText(null);
        if(txtPassword.getText().trim().equals("")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            passwordLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_btnResetAccFormActionPerformed

    private void tbl_managersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_managersMouseClicked
        btnViewMg.setVisible(true);
        btnDelMg.setVisible(true);
            
        defaulttbl_2_view = (DefaultTableModel)tbl_managers.getModel();
        int selectIndex = tbl_managers.getSelectedRow();

        int id = Integer.parseInt(defaulttbl_2_view.getValueAt(selectIndex, 0).toString());
            
        try {
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_managers where id=?");
            sqlQueryCheck.setInt(1, id);
            res = sqlQueryCheck.executeQuery();

            while(res.next()) {
                Admin_AccessMG_Credentials.serial_no    = res.getString("serial_no");
                Admin_AccessMG_Credentials.id_no        = res.getString("id_no");
                Admin_AccessMG_Credentials.date_ofbirth = res.getString("date_ofbirth");
                Admin_AccessMG_Credentials.fullname     = res.getString("fullname");
                Admin_AccessMG_Credentials.gender       = res.getString("gender");
                Admin_AccessMG_Credentials.email        = res.getString("email");
                Admin_AccessMG_Credentials.phone        = res.getString("phone");
            }
        } catch (Exception ex) {
            Logger.getLogger(Page3_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // displaying specific user info
        mgSerial.setText(Admin_AccessMG_Credentials.serial_no);
        mgIdNo.setText(Admin_AccessMG_Credentials.id_no);
        mgDob.setText(Admin_AccessMG_Credentials.date_ofbirth);
        mgFname.setText(Admin_AccessMG_Credentials.fullname);
        mgGender.setText(Admin_AccessMG_Credentials.gender);
        mgEmail.setText(Admin_AccessMG_Credentials.email);
        mgPhone.setText("0"+Admin_AccessMG_Credentials.phone);
    }//GEN-LAST:event_tbl_managersMouseClicked

    private void txtSettings1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSettings1MouseClicked
        Page7_Report genReport = new Page7_Report();
        this.dispose();
        genReport.setVisible(true);
    }//GEN-LAST:event_txtSettings1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnDelMg;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JButton btnGoToAddMg;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnResetAccForm;
    private javax.swing.JButton btnShowAllMg;
    private javax.swing.JButton btnViewMg;
    private javax.swing.JTextField emailLine;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFname;
    private javax.swing.JLabel errorId;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel errorReg;
    private javax.swing.JTextField fnameLine;
    private javax.swing.JTextField idnoLine;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mgDob;
    private javax.swing.JLabel mgEmail;
    private javax.swing.JLabel mgFname;
    private javax.swing.JLabel mgGender;
    private javax.swing.JLabel mgIdNo;
    private javax.swing.JLabel mgPhone;
    private javax.swing.JLabel mgSerial;
    private javax.swing.JTextField passwordLine;
    private javax.swing.JTextField phoneLine;
    private javax.swing.JTextField serialLine;
    private javax.swing.JLabel sideBarFname;
    private javax.swing.JLabel sideBarOperator;
    private rojeru_san.complementos.RSTableMetro tbl_managers;
    private javax.swing.JLabel topBarSerialNo;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtDay;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtIdNo;
    private javax.swing.JLabel txtLecturer;
    private javax.swing.JLabel txtManager;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JLabel txtSettings;
    private javax.swing.JLabel txtSettings1;
    private javax.swing.JLabel txtStudent;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true) {
            try {
                timeFormat = new SimpleDateFormat("hh:mm:ss a");
                time = timeFormat.format(Calendar.getInstance().getTime());
                txtTime.setText(time);

                dayFormat = new SimpleDateFormat("EEEE");
                day = dayFormat.format(Calendar.getInstance().getTime());
                txtDay.setText(day);

                dateFormat = new SimpleDateFormat("dd MMM yyyy"); // setting the time
                date = dateFormat.format(Calendar.getInstance().getTime());// getting current date
                txtDate.setText(date);// displaying the date to the user
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
